### ISSUE TITLE
Crypt partition and keymap at boot problem

### ISSUE THREAD

**Issue by rapha8l** [pop-os/pop#120]
**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**

Keymap is set to french azerty at install, and disk is encrypted.
Though at boot time, when invited to enter my crypt partition password, keyamp is qwerty 

**Steps to reproduce (if you know)**
Any installed Pop! OS in non qwerty with crypt disk setup

**Expected behavior**
Keymap at boot should be the same as the X one

**Other Notes**

Thanks

**Comment by sramkrishna** [comment]
We don't have a non-qwerty keyboard here that we can test.  I suppose we could just set something and see what it does.

**Comment by ntl** [comment]
I believe I ran into this problem. I'm a dvorak user and found that I needed to type my password in qwerty in order to boot with my encrypted root filesystem. I found this bug report that outlined the issue: https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/1719612

The workaround given [here](https://askubuntu.com/questions/977489/keyboard-layout-in-luks-prompt) worked for me. Specifically:

```
sudo ln -s /etc/console-setup/cached_UTF-8_del.kmap.gz /etc/console-setup/cached.kmap.gz
sudo update-initramfs -u
```

**Comment by sramkrishna** [comment]
@mmstick - do you think this is something you can test?  I know that we do ship keyboards that are not en_US.

**Comment by brs17** [comment]
Following the upstream bug report, it looks like a patch has fixed this issue for 18.04. Can confirm it is fixed in the daily release of Ubuntu 18.04.

**Comment by brs17** [comment]
Looks like the bug is fixed upstream and fixes the issue in early builds of Ubuntu 18.04. Once Pop!_OS 18.04 is in a position to test this, I shall.

**Comment by ariadacapo** [comment]
This is definitely still an issue in Pop!_OS 18.04.

To reproduce, 
1. Select the French keyboard during installation and set up your encryption passphrase as 10 times "a" (either directly typing them by typing the Q-labeled key on a US keyboard, or copy-pasting them from the keyboard selection test box). 
2. Complete install, reboot at end of install
3. The cryptsetup entry field shows up. The only way to enter the password is by pressing the A-labeled key on a US keyboard.

It is hard for the user to figure out what is happening, because all of the password entries are masked.

**Comment by brs17** [comment]
I believe this was recently fixed with https://github.com/pop-os/distinst/pull/120 so I am going to close the issue.
