### ISSUE TITLE
Dummy Output sound after upgrade to 20.10

### ISSUE THREAD

**Issue by ivanqueiroz** [pop-os/pop#1395]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pulseaudio:
  Instalado: 1:13.99.2-1ubuntu2
  Candidato: 1:13.99.2-1ubuntu2
  Tabela de versão:
 *** 1:13.99.2-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:13.99.2-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages

**Issue/Bug Description:**

After upgrade for 20.10 the SO detects Dummy Output or HDMI output only (when I'm connected in my second monitor). When I plug a headset don't show the menu of detection. So I have to go to terminal and kill pulseaudio (pulseaudio -k) to back to normal. I tried the steps of https://support.system76.com/articles/audio/, but don't work for me.

**Steps to reproduce (if you know):**

Login only, my notebook is Dell i15-7559-A30. 

System Information
	Manufacturer: Dell Inc.
	Product Name: Inspiron 7559
	Version: 1.3.1

**Expected behavior:**

Detect Speakers out and headset (when plug in).

**Other Notes:**
Maybe related to this Ubuntu issue -> https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1901975

![2020-11-16_09-59](https://user-images.githubusercontent.com/680864/99256284-f07a1180-27f3-11eb-8558-5b464a446e4c.png)
![2020-11-16_09-58](https://user-images.githubusercontent.com/680864/99256289-f112a800-27f3-11eb-9e28-f9cf096499e4.png)

[pa-info-dummy-out.txt](https://github.com/pop-os/pop/files/5546396/pa-info-dummy-out.txt)
[pa-info-after-kill-pulse.txt](https://github.com/pop-os/pop/files/5546397/pa-info-after-kill-pulse.txt)
[pa-info-dummy.txt](https://github.com/pop-os/pop/files/5546398/pa-info-dummy.txt)

**Comment by ruanitto** [comment]
I have same problem. Solved with this:

https://support.system76.com/articles/audio/

**Comment by ivanqueiroz** [comment]
I tried, but after some reboots, the problems came back. So I have to execute pulseaudio -k every time.

**Comment by ivanqueiroz** [comment]
I think that problem is because of the combination of NVIDIA + Intel Sound + External monitor in HDMI. 

After searching a lot, I found some instructions for set default output in [https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_sink](https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_sink).

In my /etc/pulse/default.pa I put the stereo device as default, and the problem was gone.

**Comment by agucova** [comment]
This happened to me without having an external monitor, just under normal laptop usage (I'm using a GTX 1650M) after upgrading, no special audio settings.

**Comment by ivanqueiroz** [comment]
Back to happen with me too. I tried everthing, but no success. I put the command ```pulseaudio -k``` on login to handle this

**Comment by agucova** [comment]
In my case, I killed PulseAudio several times until it started working? I'm not sure what I can do to debug it if it happens again.

**Comment by ivanqueiroz** [comment]
> In my case, I killed PulseAudio several times until it started working? I'm not sure what I can do to debug it if it happens again.
> EDIT: It's happening on every restart and `systemctl restart --user pulseaudio` seems to do the trick.

When you use ```pulseaudio -k``` kill daemon and starts automaticaly, so I put a script on long calling the command.

**Comment by Sebastiangperez** [comment]
So , this bug still exist ?? i switched to fedora from ubuntu because every time  i upgrade the system the sound stops working.

**Comment by agucova** [comment]
It does. I now have a pulseaudio reboot on startup to solve this issue. Did you also see the Dummy Output on start?

**Comment by ivanqueiroz** [comment]
This problem its very common on intel audio on Dell Laptops with NVIDIA cards, when I searched on internet, I saw this pattern. Another thing is when its used a second monitor on HDMI input.

**Comment by agucova** [comment]
I have an HP laptop with Intel + Nvidia and no second monitor. I'm not sure
if I see that pattern. (though Nvidia may still be related)

**Comment by bflanagin** [comment]
I've seen this issues a few times throughout my experience with Desktop Linux. Like @ivanqueiroz says the most sure fire way to fix the problem is to restart the service at login. Though `pulseaudio -k` will do the trick you can also use `systemctl --user stop pulseaudio.{socket,service}` which is the suggested way to restart pulseaudio on systemd system like Pop!_OS.

**Comment by DanielJoyce** [comment]
Audio is a mess. My pixel C earbuds work/don't work. I can sometimes get them to work by swithing between usb-c ports, most often they don't show up as SPDIF capable, but sometimes switching usb-c ports fixes it.

**Comment by u007** [comment]
im having issue now on popos 22.04, and it uses pipewire. all the documentation are using alsa or pulse audio which did not work for my case
