### ISSUE TITLE
Window screen tearing during resizing via dragging

### ISSUE THREAD

**Issue by nagha95** [pop-os/pop#1429]
**(1) Issue/Bug Description:** Windows considerably stutter and flicker with occasional graphical distortion while resizing through dragging on any edges. This is especially an issue when resizing a window with video playing, such as Firefox's picture-in-picture mode. Additionally, Firefox's picture-in-picture window, when dragged to resize from the left side, not only stutters and flickers, but also jumps around to the left side of the screen and starts slipping out of view.

**(2) Steps to reproduce (if you know):** 

- Resize a window by dragging on one of its edges.
- Resize a Firefox picture-in-picture window by dragging on one of its edges, especially the left edge.

**(3) Expected behavior:** Window resizing must animate smoothly with no stuttering, flickering or any degree of graphical distortion.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 ```

**(5) Gnome Shell version:**
```
GNOME Shell 3.36.4
```

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```
pop-shell:
  Installed: 1.0.0~1603994289~20.04~ecc9b38
  Candidate: 1.0.0~1603994289~20.04~ecc9b38
  Version table:
 *** 1.0.0~1603994289~20.04~ecc9b38 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
        100 /var/lib/dpkg/status
```

**(7) Where was Pop Shell installed from:** Whole operating system was installed via https://pop-iso.sfo2.cdn.digitaloceanspaces.com/20.04/amd64/intel/13/pop-os_20.04_amd64_intel_13.iso

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** HP Laptop 15-bs1xx monitor (1 x 1080p, Primary (Horizontal)).

**(9) Other Installed/Enabled Extensions:**
```
['dash-to-dock@micxgx.gmail.com', 'gsconnect@andyholmes.github.io']
```

**(10) Other Notes:** Same issue also occurs on Wayland. Used Ubuntu 20.04 LTS a few days ago and it wasn't an issue.

**Comment by timo-f** [comment]
Same issue here. With the tearfree option many other things stop working

**Comment by crispy-cat** [comment]
Had this issue with nvidia drivers 455.28, switching to 455.38 appeared to have fixed it for a while but it's back again. 

i7-10875H / RTX 2070 Super Max-Q / Pop 20.10

**Comment by cichy1173** [comment]
Has someone checked MESA 21.0 drivers? Is it repairing the problem?

**Comment by Gzman** [comment]
I also still have this issue..
Pop!_OS 20.10
Intel Core i7-5600u
Mesa Intel HD Graphics 5500 (BDW GT2)

**Comment by istomyang** [comment]
> I have the same issue, and it appears it is the same for all intel graphics users.
> 
> You can also see posts [on reddit here by me](https://www.reddit.com/r/pop_os/comments/jq96nk/graphics_corruption_on_window_resize_pop_2004_and/) and [by others here](https://www.reddit.com/r/pop_os/comments/jmpxbe/screen_tearing_with_intel_graphics/).
> 
> [This video I grabbed](https://www.youtube.com/watch?v=bG2lNq-Nk9g) shows the problem.
> 
> The solution suggested is this:
> 
> > The file must reside on /etc indeed, create the folder if it is missing (probably it is):
> > `sudo mkdir -p /etc/X11/xorg.conf.d`
> > then create the file:
> > `sudo touch /etc/X11/xorg.conf.d/20-intel.conf`
> > and you can now edit it:
> > `sudo gedit /etc/X11/xorg.conf.d/20-intel.conf`
> > I recommend this setting:
> 
> ```
>    Section "Device"
>       Identifier  "Intel Graphics"
>       Driver      "intel"
>       Option      "SwapBuffersWait" "true"
>       Option      "TearFree" "true"
>    EndSection
> ```
> 
> However this is a workaround and **causes problems** to (at least) **Chrome** with random freezes, consistently failing to go to full screen when playing a video that started windowed. [Here](https://youtu.be/LArYmsNdZsg) is a video demonstrating this problem. The window controls of Chrome work, as you can see I can pull tabs out and I can use the top right corner button to close. So it's not completely crashed, but it's not healthy.
> 
> Thank you.
> 
> System details:
> 
> Hardware:
> 
> ```
> Machine:   Type: Laptop System: LENOVO product: 20FW003KMC v: ThinkPad T460p serial: <superuser/root required> 
>            Mobo: LENOVO model: 20FW003KMC v: 0B98417 WIN serial: <superuser/root required> UEFI: LENOVO v: R07ET92W (2.32 ) 
>            date: 07/28/2019 
> CPU:       Info: Quad Core model: Intel Core i7-6820HQ bits: 64 type: MT MCP L2 cache: 8192 KiB 
>            Speed: 1213 MHz min/max: 800/3600 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 5: 900 6: 2812 
>            7: 1842 8: 1880 
> Graphics:  Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
>            Device-2: Chicony Integrated Camera type: USB driver: uvcvideo 
>            Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 2560x1440~60Hz 
>            OpenGL: renderer: Mesa Intel HD Graphics 530 (SKL GT2) v: 4.6 Mesa 20.2.1 
> Drives:    Local Storage: total: 1.05 TiB used: 217.59 GiB (20.3%) 
>            ID-1: /dev/mmcblk0 model: SD16G size: 120.02 GiB 
>            ID-2: /dev/nvme0n1 vendor: A-Data model: SX8200PNP size: 953.87 GiB 
> ```
> 
> ```
> NAME="Pop!_OS"
> VERSION="20.10"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 20.10"
> VERSION_ID="20.10"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=groovy
> UBUNTU_CODENAME=groovy
> LOGO=distributor-logo-pop-os
> ```
> 
> > GNOME Shell 3.38.1
> 
> ```
> pop-shell:
>   Installed: 1.0.0~1604688242~20.10~d1d2b0e
>   Candidate: 1.0.0~1604688242~20.10~d1d2b0e
>   Version table:
>  *** 1.0.0~1604688242~20.10~d1d2b0e 1001
>        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
>        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
>         100 /var/lib/dpkg/status
> ```

Thank you for your video! A picture is worth a thousand words.
I am a user and can provide some infos.

- This issue just occur in X11 with modesetting (KMS) enabled. 
- In Arch Linux, Ubuntu, same x11 with modesetting has no issue, very normal. ( Just in intel card ) You may ask me if having some special config? Answer is No! 
- The solution now is using intel driver. https://wiki.archlinux.org/index.php/intel_graphics
- In my computer, I use those code below and a new issue occur: lose frames in launch application animation.

```
 Section "Device"
      Identifier  "Intel Graphics"
      Driver      "intel"
      Option      "AccelMethod"  "sna"
   EndSection
```
- This is my opinion: Fu** Nvidia, and X11 is disaster.
- Well, in this issue, it's a question of Pop! OS. He did many works in Graphics cards, so it's different from other x11 config. I can't copy files directly from other system.

**Comment by ppnon** [comment]
Hi guys, I have tried different settings in the 20-intel.conf file and the only one that works for me was this:

```
Section "Device"
 	Identifier  "Intel Graphics"
 	Driver      "intel"
 	Option      "AccelMethod"  "uxa"
EndSection
```
and after restart or re-login purge the xserver-xorg-video-intel package:
```
sudo apt purge xserver-xorg-video-intel
```

When I tried with **sna** [AccelMethod](https://wiki.archlinux.org/index.php/intel_graphics#AccelMethod) the performance dropped a lot and I experienced the chrome issue described by @spxak1 instread with **uxa** I only feel slow performance sometimes, but it improves if hardware acceleration is disabled in Chrome settings.

This are my system details:
> OS: Pop!_OS 20.04 LTS x86_64 
> Host: 20JS0004US ThinkPad T470s W10DG
> Kernel: 5.8.0-7630-generic 
> Resolution: 1920x1080, 1920x1080
> CPU: Intel i7-6600U (4) @ 3.400GHz
> GPU: Intel Skylake GT2 [HD Graphics 520]

I hope this can help you and I'm sorry if my english is not very good.

**Comment by fidelisakilan** [comment]
i used fedora 33 and there is no graphical issue in it also there is no conf file for intel. just with ubuntu and pop it is like this.

**Comment by FelipeGangrel** [comment]
> i used fedora 33 and there is no graphical issue in it also there is no conf file for intel. just with ubuntu and pop it is like this.

Same here. I'm using Fedora 33 and no issues whatsoever (x11 and Wayland).

**Comment by LeCodingWolfie** [comment]
> > I have the same issue, and it appears it is the same for all intel graphics users.
> > You can also see posts [on reddit here by me](https://www.reddit.com/r/pop_os/comments/jq96nk/graphics_corruption_on_window_resize_pop_2004_and/) and [by others here](https://www.reddit.com/r/pop_os/comments/jmpxbe/screen_tearing_with_intel_graphics/).
> > [This video I grabbed](https://www.youtube.com/watch?v=bG2lNq-Nk9g) shows the problem.
> > The solution suggested is this:
> > > The file must reside on /etc indeed, create the folder if it is missing (probably it is):
> > > `sudo mkdir -p /etc/X11/xorg.conf.d`
> > > then create the file:
> > > `sudo touch /etc/X11/xorg.conf.d/20-intel.conf`
> > > and you can now edit it:
> > > `sudo gedit /etc/X11/xorg.conf.d/20-intel.conf`
> > > I recommend this setting:
> > 
> > 
> > ```
> >    Section "Device"
> >       Identifier  "Intel Graphics"
> >       Driver      "intel"
> >       Option      "SwapBuffersWait" "true"
> >       Option      "TearFree" "true"
> >    EndSection
> > ```
> > 
> > 
> > However this is a workaround and **causes problems** to (at least) **Chrome** with random freezes, consistently failing to go to full screen when playing a video that started windowed. [Here](https://youtu.be/LArYmsNdZsg) is a video demonstrating this problem. The window controls of Chrome work, as you can see I can pull tabs out and I can use the top right corner button to close. So it's not completely crashed, but it's not healthy.
> > Thank you.
> > System details:
> > Hardware:
> > ```
> > Machine:   Type: Laptop System: LENOVO product: 20FW003KMC v: ThinkPad T460p serial: <superuser/root required> 
> >            Mobo: LENOVO model: 20FW003KMC v: 0B98417 WIN serial: <superuser/root required> UEFI: LENOVO v: R07ET92W (2.32 ) 
> >            date: 07/28/2019 
> > CPU:       Info: Quad Core model: Intel Core i7-6820HQ bits: 64 type: MT MCP L2 cache: 8192 KiB 
> >            Speed: 1213 MHz min/max: 800/3600 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 5: 900 6: 2812 
> >            7: 1842 8: 1880 
> > Graphics:  Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
> >            Device-2: Chicony Integrated Camera type: USB driver: uvcvideo 
> >            Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 2560x1440~60Hz 
> >            OpenGL: renderer: Mesa Intel HD Graphics 530 (SKL GT2) v: 4.6 Mesa 20.2.1 
> > Drives:    Local Storage: total: 1.05 TiB used: 217.59 GiB (20.3%) 
> >            ID-1: /dev/mmcblk0 model: SD16G size: 120.02 GiB 
> >            ID-2: /dev/nvme0n1 vendor: A-Data model: SX8200PNP size: 953.87 GiB 
> > ```
> > 
> > 
> > ```
> > NAME="Pop!_OS"
> > VERSION="20.10"
> > ID=pop
> > ID_LIKE="ubuntu debian"
> > PRETTY_NAME="Pop!_OS 20.10"
> > VERSION_ID="20.10"
> > HOME_URL="https://pop.system76.com"
> > SUPPORT_URL="https://support.system76.com"
> > BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> > PRIVACY_POLICY_URL="https://system76.com/privacy"
> > VERSION_CODENAME=groovy
> > UBUNTU_CODENAME=groovy
> > LOGO=distributor-logo-pop-os
> > ```
> > 
> > 
> > > GNOME Shell 3.38.1
> > 
> > 
> > ```
> > pop-shell:
> >   Installed: 1.0.0~1604688242~20.10~d1d2b0e
> >   Candidate: 1.0.0~1604688242~20.10~d1d2b0e
> >   Version table:
> >  *** 1.0.0~1604688242~20.10~d1d2b0e 1001
> >        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
> >        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
> >         100 /var/lib/dpkg/status
> > ```
> 
> Thank you for your video! A picture is worth a thousand words.
> I am a user and can provide some infos.
> 
>     * This issue just occur in X11 with modesetting (KMS) enabled.
> 
>     * In Arch Linux, Ubuntu, same x11 with modesetting has no issue, very normal. ( Just in intel card ) You may ask me if having some special config? Answer is No!
> 
>     * The solution now is using intel driver. https://wiki.archlinux.org/index.php/intel_graphics
> 
>     * In my computer, I use those code below and a new issue occur: lose frames in launch application animation.
> 
> 
> ```
>  Section "Device"
>       Identifier  "Intel Graphics"
>       Driver      "intel"
>       Option      "AccelMethod"  "sna"
>    EndSection
> ```
> 
>     * This is my opinion: Fu** Nvidia, and X11 is disaster.
> 
>     * Well, in this issue, it's a question of Pop! OS. He did many works in Graphics cards, so it's different from other x11 config. I can't copy files directly from other system.

According to my research — that led me here, because I have the same problem —, **this is not a problem only with X11 display, but specifically the** [**driver i915 from Intel**](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1896627). **And it not only happens with Pop_OS, but also with** [**other Ubuntu-based distros**](https://discourse.ubuntubudgie.org/t/screen-flickers-on-multiple-computers-20-10/4511)**, and quite probably,** [**Ubuntu in general**](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1896627) — either on [20.10](https://discourse.ubuntubudgie.org/t/screen-glitching-problem-with-20-04/3661/3) or [20.04](https://discourse.ubuntubudgie.org/t/screen-glitching-problem-with-20-04/3661/7) version —.

**Comment by LeCodingWolfie** [comment]
> > I have the same issue, and it appears it is the same for all intel graphics users.
> > You can also see posts [on reddit here by me](https://www.reddit.com/r/pop_os/comments/jq96nk/graphics_corruption_on_window_resize_pop_2004_and/) and [by others here](https://www.reddit.com/r/pop_os/comments/jmpxbe/screen_tearing_with_intel_graphics/).
> > [This video I grabbed](https://www.youtube.com/watch?v=bG2lNq-Nk9g) shows the problem.
> > The solution suggested is this:
> > > The file must reside on /etc indeed, create the folder if it is missing (probably it is):
> > > `sudo mkdir -p /etc/X11/xorg.conf.d`
> > > then create the file:
> > > `sudo touch /etc/X11/xorg.conf.d/20-intel.conf`
> > > and you can now edit it:
> > > `sudo gedit /etc/X11/xorg.conf.d/20-intel.conf`
> > > I recommend this setting:
> > 
> > 
> > ```
> >    Section "Device"
> >       Identifier  "Intel Graphics"
> >       Driver      "intel"
> >       Option      "SwapBuffersWait" "true"
> >       Option      "TearFree" "true"
> >    EndSection
> > ```
> > 
> > 
> > However this is a workaround and **causes problems** to (at least) **Chrome** with random freezes, consistently failing to go to full screen when playing a video that started windowed. [Here](https://youtu.be/LArYmsNdZsg) is a video demonstrating this problem. The window controls of Chrome work, as you can see I can pull tabs out and I can use the top right corner button to close. So it's not completely crashed, but it's not healthy.
> > Thank you.
> > System details:
> > Hardware:
> > ```
> > Machine:   Type: Laptop System: LENOVO product: 20FW003KMC v: ThinkPad T460p serial: <superuser/root required> 
> >            Mobo: LENOVO model: 20FW003KMC v: 0B98417 WIN serial: <superuser/root required> UEFI: LENOVO v: R07ET92W (2.32 ) 
> >            date: 07/28/2019 
> > CPU:       Info: Quad Core model: Intel Core i7-6820HQ bits: 64 type: MT MCP L2 cache: 8192 KiB 
> >            Speed: 1213 MHz min/max: 800/3600 MHz Core speeds (MHz): 1: 900 2: 900 3: 900 4: 900 5: 900 6: 2812 
> >            7: 1842 8: 1880 
> > Graphics:  Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
> >            Device-2: Chicony Integrated Camera type: USB driver: uvcvideo 
> >            Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 2560x1440~60Hz 
> >            OpenGL: renderer: Mesa Intel HD Graphics 530 (SKL GT2) v: 4.6 Mesa 20.2.1 
> > Drives:    Local Storage: total: 1.05 TiB used: 217.59 GiB (20.3%) 
> >            ID-1: /dev/mmcblk0 model: SD16G size: 120.02 GiB 
> >            ID-2: /dev/nvme0n1 vendor: A-Data model: SX8200PNP size: 953.87 GiB 
> > ```
> > 
> > 
> > ```
> > NAME="Pop!_OS"
> > VERSION="20.10"
> > ID=pop
> > ID_LIKE="ubuntu debian"
> > PRETTY_NAME="Pop!_OS 20.10"
> > VERSION_ID="20.10"
> > HOME_URL="https://pop.system76.com"
> > SUPPORT_URL="https://support.system76.com"
> > BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> > PRIVACY_POLICY_URL="https://system76.com/privacy"
> > VERSION_CODENAME=groovy
> > UBUNTU_CODENAME=groovy
> > LOGO=distributor-logo-pop-os
> > ```
> > 
> > 
> > > GNOME Shell 3.38.1
> > 
> > 
> > ```
> > pop-shell:
> >   Installed: 1.0.0~1604688242~20.10~d1d2b0e
> >   Candidate: 1.0.0~1604688242~20.10~d1d2b0e
> >   Version table:
> >  *** 1.0.0~1604688242~20.10~d1d2b0e 1001
> >        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
> >        1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
> >         100 /var/lib/dpkg/status
> > ```
> 
> Thank you for your video! A picture is worth a thousand words.
> I am a user and can provide some infos.
> 
>     * This issue just occur in X11 with modesetting (KMS) enabled.
> 
>     * In Arch Linux, Ubuntu, same x11 with modesetting has no issue, very normal. ( Just in intel card ) You may ask me if having some special config? Answer is No!
> 
>     * The solution now is using intel driver. https://wiki.archlinux.org/index.php/intel_graphics
> 
>     * In my computer, I use those code below and a new issue occur: lose frames in launch application animation.
> 
> 
> ```
>  Section "Device"
>       Identifier  "Intel Graphics"
>       Driver      "intel"
>       Option      "AccelMethod"  "sna"
>    EndSection
> ```
> 
>     * This is my opinion: Fu** Nvidia, and X11 is disaster.
> 
>     * Well, in this issue, it's a question of Pop! OS. He did many works in Graphics cards, so it's different from other x11 config. I can't copy files directly from other system.

_**[Extracted from @istomyang reply](https://github.com/pop-os/pop/issues/1429#issuecomment-748602712)**_

According to my research — that led me here, because I have the same problem —, **this is not a problem only with X11 display, but specifically the driver i915 from Intel [1]. Particularly, it might be a Linux kernel problem, because this problem was patched at Ubuntu Linux package (kernel) 5.8.0-34.37 [2] — probably on Ubuntu 20.04, and even on 21.04 [3, 4]. And it not only happens with Pop_OS, but also with other Ubuntu-based distros [5], and quite probably, Ubuntu in general [1]** — and even on 20.10 version [5]. 

Furthermore, with self-research — that means from the evaluation of the problem on my own PC —, I found out that I also do have i915 driver and X11 display, by using `inxi -G` command on the terminal. And as @istomyang noted. that this problem does just occur with `modesetting` enabled [6], and I have it enabled! 

**`inxi -G` output:**

```
Graphics:  Device-1: Intel UHD Graphics 630 driver: i915 v: kernel 
           Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia v: 460.32.03 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 20.2.6
```

However. @istomyang also noted that using Intel driver is the solution [6], but, as it turns out, with both self and "normal" research, i915 Intel driver — which I do have — might be the problem [1]. Although, @istomyang redirected to an [Arch Linux wiki page](https://wiki.archlinux.org/index.php/intel_graphics#Tearing) of the subject — Intel drivers —, which does tells the solution to this problem, without the creation of the file in comparison to @spxak1 one.

Furthermore, with that self-research, I found that `/etc/X11` folder does not have `xorg.conf.d` folder, but `/usr/share/X11/` does. Therefore, that's why the creation of the folder is necessary. However, usr one does not have `20-intel.conf` file, even if it does have that folder, only other `.conf` files concerning AMD and Nvidia. Thus, creating that file is also required. Although I'm confused becuase of that **— why usr does not have that file if it has the folder; and why etc does not have the folder already — if there's an explanation, I'll be glad to hear it out.**

**.conf files from my `/usr/share/X11/xorg.conf.d` folder:**

```
10-amdgpu.conf  10-quirks.conf  11-nvidia-offload.conf  70-wacom.conf
10-nvidia.conf  10-radeon.conf  40-libinput.conf
```

And finally, with self-experience with this bug, the tearing/flickering/screen glitching can be produced by actions like: clicking on activities, selecting options on Firefox, scrolling (sometimes), when a notification appears and others.

**I hope all this information could be useful both for you and for System76 team.**

**References:**

[1] https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1896091 _(i915 driver-related bug)_
[2] https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1896091/comments/65 _(Comment about patch on Ubuntu)_
[3] https://launchpad.net/ubuntu/+source/linux-hwe-5.8/5.8.0-34.37~20.04.2 _(Patch on Ubuntu 20.04 to linux-hwe)_
[4] https://launchpad.net/ubuntu/+source/linux/5.8.0-34.37+21.04.1 _(Patch on Ubuntu 21,04)_
[5] https://discourse.ubuntubudgie.org/t/screen-flickers-on-multiple-computers-20-10/4511 _(Problem posted on Ubuntu Budgie distro community)_
[6] https://github.com/pop-os/pop/issues/1429#issuecomment-748602712 _(Reply posted by @istomyang)_

_**Important note:** I am a fresh Linux user — I joined to the Linux environment when this year started. I do not have a "moderate" knowledge of the OS — and also a fresh programmer. Please correct me if I did a mistake, becuase I only researched about this problem._

_PD: As the least important subject, I also interestingly found in an [Ubuntu Budgie community site](https://discourse.ubuntubudgie.org/t/screen-glitching-problem-with-20-04/3661/4)  — which I used as foundation to research all about this problem even if it wasn't related with the problem, because only one reply did — a @spxak1 related solution, but without the creation of the file._

**Comment by prashanthwagle** [comment]
> I have tried Wayland, there electron apps and chrome performance is poor, chrome sometime lags when closing tab .Also in VS code the scroll is broken in wayland

A Simple Video recording and using OBS studio is a pain in Wayland

**Comment by nubunto** [comment]
Happens to me as well on 20.04 and Intel. Driving me away from Pop!_OS to be honest...

**Comment by bflanagin** [comment]
@LeCodingWolfie that was an amazing breakdown! A simple and abbreviated answer to you pondering is that in automating xorg configurations (everything used to be manual) the maintainers decided the configs should be moved /usr/ which frees up /etc/X11 for overrides and the like. Why an intel config doesn't exist there should be pretty clear given this thread. What works for one doesn't work for all and thus its just left to the defaults provided by the driver itself. For a lot of hardware the defaults work fine, but when they don't, they really don't. 

We at system76 try to test all the hardware we provide to make sure issues like this don't happen on our equipment, but the search for a 'real fix' for everyone is still nebulously in the future. We keep an eye on this thread for any insights you all may have and thank you for the time it takes to report an issue.

**Comment by j3st3r68** [comment]
There is a similar bug report in Ubuntu Mutter package and it seems that mutter 3.38.2+Xorg 1.20.10 should work fine.

Meanwhile I found a workaround using Intel instead modesetting driver creating /etc/X11/xorg.conf.d/20-intel-grapichs.conf with these settings (I have hybrid Intel-nVidia graphics):
```
Section "Module"
    Load "nvidia"
EndSection

Section "Device"
    Identifier  "Intel Graphics"
    Driver      "intel"
EndSection
```
This is my system configuration:
```
OS: Pop!_OS 20.10 x86_64 
Host: X556UJ 1.0 
Kernel: 5.8.0-7642-generic 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 3.38.2 
WM: Mutter 
WM Theme: Pop 
heme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-6500U (4) @ 3.100GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
GPU: NVIDIA GeForce 920M 
Memory: 2446MiB / 7760MiB 
```
and **```inxi -G```** output:
```
Graphics:  Device-1: Intel Skylake GT2 [HD Graphics 520] driver: i915 v: kernel 
           Device-2: NVIDIA GK208BM [GeForce 920M] driver: nvidia v: 460.39 
           Device-3: Realtek USB Camera type: USB driver: uvcvideo 
           Display: x11 server: X.Org 1.20.9 driver: intel,nvidia resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 520 (SKL GT2) v: 4.6 Mesa 20.3.2 
```

**Comment by spxak1** [comment]
I don't know how much such the conf file suggested by @j3st3r68  does, but it certainly stopped the issue on my T460p and so far there have been none of the other problems that the extra options present for Chrome (sluggish and erratic performance). 

Thanks for that, but I'm curious, as there is no option for intel other than the driver which I'd guess is what is used anyway? Or is this a different driver?

**Comment by j3st3r68** [comment]
> Thanks for that, but I'm curious, as there is no option for intel other than the driver which I'd guess is what is used anyway? Or is this a different driver?

Without 20-intel-grapichs.conf file in /etc/X11/xorg.conf.d the default driver used for Intel GPU is "modesetting" (not intel), which is probably responsible for the bug.

**Comment by spxak1** [comment]
> > Thanks for that, but I'm curious, as there is no option for intel other than the driver which I'd guess is what is used anyway? Or is this a different driver?
> 
> Yes, it's a different driver. Without 20-intel-grapichs.conf file in /etc/X11/xorg.conf.d the default driver used for Intel GPU is "modesetting" (not intel), which is probably responsible for the bug (also the Xorg 1.20.09 could be involved).

Thanks for that. In which case this means that setting the driver to intel in that file is the same as using **nomodeset** in the kernel? Because the latter also solves the issue.

Thanks again, I will do some testing now.

**Comment by j3st3r68** [comment]
> Thanks for that. In which case this means that setting the driver to intel in that file is the same as using **nomodeset** in the kernel? Because the latter also solves the issue.

I'm not an expert but I suppose that **nomodeset** parameter avoid to load the modesetting kernel graphic driver at boot time, so when X starts it looks for another available driver and use intel. The file instead is read when X starts and replaces modesetting with intel driver. The final effect should be the same.
Maybe kernel guru guys could have extra info.

**Comment by spxak1** [comment]
After some testing, setting the conf file that @j3st3r68  suggested breaks Google Meet on Chrome (presenting won't work, and eventually chrome crashes). 

Thanks again.

**Comment by j3st3r68** [comment]
> After some testing, setting the conf file that @j3st3r68 suggested breaks Google Meet on Chrome (presenting won't work, and eventually chrome crashes).
> 
> Thanks again.

I don't use Chrome/Meet very often but I made some tests after your post presenting several applications windows form my pc to my smartphone and I had no issues (attached the test with terminal window presentation).
Chrome version is 88.0.4324.150

![IMG_2196](https://user-images.githubusercontent.com/78619704/107533774-8fc65f00-6bbf-11eb-9a4b-1328cbd7d01a.jpg)

**Comment by spxak1** [comment]
Much appreciated! I will do some further testing. Thanks again.

**Comment by Mennaruuk** [comment]
Even after switching to Wayland, window resizing animations remain not smooth for many programs (the pattern I think I see here is non-system programs):

https://user-images.githubusercontent.com/52135169/108731016-1fdaa180-74fa-11eb-9d10-aacc51402828.mp4

**Comment by mitsos1os** [comment]
> Looks like a driver issue, I've had the issue on both Ubuntu 20.10 and Pop 20.10, so probably from the main Ubuntu repo's. I resolved this issue by updating the drivers to the latest commit builds from from oibafs PPA.
> 
> Hopefully will be backported at some point.
> 
> https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

Used this repository to update drivers and issue resolved on my system with details:
- **Model**: XPS 13 9360
- **CPU:** Core i5-7200U
- **GPU:** IntelHD 620
- **OS:** PopOS 20.10 kernel 5.11.0-7612

**Comment by LordChaos73** [comment]
Can you try these driver settings:

```
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "DRI" "3"
  Option "TripleBuffer" "true"
  Option "TearFree" "true"
  Option "SwapBuffersWait" "true"
EndSection
```

```
Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.9 driver: i915 resolution: 2560x1440~60Hz 
           OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.0.0
```

`5.11.0-7612-generic x86_64 GNU/Linux`

Pop!OS 20.04, Lenovo X1 Carbon (6th gen), fractional scaling set to 150%.

**Comment by khanhicetea** [comment]
> Can you try these driver settings:
> 
> ```
> Section "Device"
>   Identifier "Intel Graphics"
>   Driver "intel"
>   Option "DRI" "3"
>   Option "TripleBuffer" "true"
>   Option "TearFree" "true"
>   Option "SwapBuffersWait" "true"
> EndSection
> ```
> 
> ```
> Graphics:  Device-1: Intel UHD Graphics 620 driver: i915 v: kernel 
>            Display: x11 server: X.Org 1.20.9 driver: i915 resolution: 2560x1440~60Hz 
>            OpenGL: renderer: Mesa Intel UHD Graphics 620 (KBL GT2) v: 4.6 Mesa 21.0.0
> ```
> 
> `5.11.0-7612-generic x86_64 GNU/Linux`
> 
> Pop!OS 20.04, Lenovo X1 Carbon (6th gen), fractional scaling set to 150%.

I tried this setting and it works fine (tested in 10 minutes within Chrome 10 heavy tabs)

My laptop config (Dell XPS 9310 - developer edition):

![image](https://user-images.githubusercontent.com/4528223/113852989-5aa54a00-97c7-11eb-8564-5ea7ad2324e1.png)

**Comment by khanhicetea** [comment]
It worked fine only if ( plugged power in OR used Wayland instead of X11)
So issues can be X11 or Power or both

**Comment by Arpitgoyalgg** [comment]
I switched the graphics from Integrated to NVIDIA and the flickering stopped. This issue is with the Integrated graphics and Hybrid graphics settings. Use only NVIDIA graphics and there won't be any screen tearing.

**Comment by joelostblom** [comment]
I see this issue too on a new Lemur Pro (lemp10) running PopOS with the latest updates as of today.

**Comment by Niranjan16-Ninja** [comment]
> Im having similar issue on two laptops with integrated intel graphics. Issue appeared on 20.04 and still present on 20.10.

Yeah, It's still in PopOS version 20.10 , I wonder when they'll fix it . I have attached the video for same. In addition when resize the terminal , path text are repeatedly added.
[deepin-screen-recorder_code_20210518192925.zip](https://github.com/pop-os/pop/files/6501979/deepin-screen-recorder_code_20210518192925.zip)

**Comment by gleachkr** [comment]
> I see this issue too on a new Lemur Pro (lemp10) running PopOS with the latest updates as of today.

Same here. If you find a fix, please post.

**Comment by scbj** [comment]
Same for me, the interface also jumps when **I scroll through lists**, elements are found in several places at the same time before it returns to normal. By passing the mouse over it, for example. When this happens, often my mouse has an **afterimage** (an afterimage of my mouse remains frozen in an old position while I move the "real" mouse).

In addition, it is almost **impossible to play videos** in the default player. Image is **flickering**, or has **green artifacts** all over it.

In the meantime, I have reverted to Windows 10.. 🙄

**Comment by leviport** [comment]
@scbj That sounds like a different issue to me. Even the more "severe" cases of this bug are quite minor in comparison, and they happen only briefly in specific cases. I certainly wouldn't call it a show-stopper, and the behavior you're describing sounds like a show-stopper.

**Comment by scbj** [comment]
@leviport but I've exactly the same issue as described by nourkagha :

> Windows considerably stutter and flicker with occasional graphical distortion while resizing through dragging on any edges. [...]

So I described more exactly the other graphical issues I am having with a fresh install of Pop!_OS on my new XPS.

Do i need to open another issue?  Because apart from driver issues I don't see what can cause such things (with a clean OS installation without third-party applications)

**Comment by leviport** [comment]
Right, but I'm wondering if you're seeing a different issue happening on top of that. I have a laptop that's had the artifacts when resizing windows and when dialogs appear/disappear, but it's never left mouse cursor trails or had issues playing videos. 

I'd probably make a different issue, but you can definitely continue following this one if you want to. To me it sounds like issues with the Intel drivers. 11th gen Xe graphics is so new that there might be some critical updates that still have to make their way downstream into Ubuntu/Pop. There could be some i915 kernel parameters that make it behave better in the short-term until those drivers are updated.

**Comment by davenavas** [comment]
Ok I've been trying to install linux in a laptop with terrible linux support. 

Razer blade stealth late 2016
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4
Mesa Intel® HD Graphics 620 (KBL GT2)

I freshly installed pop os after finally making everything work in ubuntu 20.04 LTS.
I did the changes needed just like in ubuntu and it is almost ready. HIDPI is really weird and wont let me change the resolution and keeps spamming a notification over and over. so I Disabled HiDPI Daemon. I changed to a usable resolution of 1080p and 100% scaling. This stops the problems with HiDPI.
**Only the glitch when resizing a window remains.**

What I can contribute is the current ubuntu 20.04LTS already fixed this problem, they might have different drivers or setting. Would it be a good idea to check that. Anyone else's computer works with ubuntu 20.04 LTS in this matter? I didn't include ubuntu 21.04 in this question because it uses wayland.

I have an awesome machine with terrible linux support :(

**Comment by davenavas** [comment]
UPDATE: I wanted to update because I got my installation working pretty decently. For anyone still having these problems with your computer with the intel UHD 620 and mesa drivers I found it might be a problem with the kernel. The glitching is reduced drastically when I installed Liquorix kernel (don't forget to reboot for changes to take effect). This makes my fresh installation almost perfect, it glitches a bit but it is i would say 95% less common. 
I've been trying to install Ubuntu 's generic kernel but I haven't have any luck. The current kernel for a fresh installation of Pop_OS! comes from system76 ppa, so I am looking to change this kernel to the one that comes from the Ubuntu repositories and test if this fixes the glitching when resizing windows. If anyone knows how to do this, that would help me test it faster.

**Comment by ExtremeCoolDude** [comment]
I'm having the exact same glitches in the video on the top most comment, it all started when I installed the orchis shell  theme, it doesn't go away after uninstalling it. I noticed that there is orchis shell theme being used in the video as well ( correct me if I'm wrong, its the same theme with those nice gaps and rounded corners)

**Comment by davenavas** [comment]
> I'm having the exact same glitches in the video on the top most (edit : 3rd or 4th) comment, it all started when I installed the orchis shell theme, it doesn't go away after uninstalling it. I noticed that there is orchis shell theme being used in the video as well ( correct me if I'm wrong, its the same theme with those nice gaps and rounded corners)

Did you try to reproduce the glitching before changing the theme, for me happens in a clean installation (including the updates). For me, it is not the theme, but i narrow it down to this version of the kernel.

**Comment by ExtremeCoolDude** [comment]
> Did you try to reproduce the glitching before changing the theme, for me happens in a clean installation (including the updates). For me, it is not the theme, but i narrow it down to this version of the kernel. 

For me the glitch happens when using a keyboard shortcut to open a terminal and the glitch started after I used that shell theme. Now that you mention it, I'm not sure if it is exacerbation of existing issue  or a completely new issue.

**Comment by danilkhromov** [comment]
It seems that the issue is fixed (at least in my case) in 21.04 update. I updated the os on two laptops and im not able to reproduce the issue anymore.

**Comment by cichy1173** [comment]
> It seems that the issue is fixed (at least in my case) in 21.04 update. I updated the os on two laptops and im not able to reproduce the issue anymore.

I have tested Pop OS 21.04 from memory stick and it is true. New version of OS is fixing this problem.

**Comment by LordChaos73** [comment]
21.04 certainly didn't solve the tearing for me. I just installed it natively on my X1Carbon gen6 and when using 150% fractional scaling on the built-in display I noticed a lot of tearing when watching a movie on Netflix for example (using Firefox).
Once again I had to create the 20-intel.conf file, this time in /etc/X11/xorg.conf.d as mentioned [here](https://github.com/pop-os/pop/issues/1429#issuecomment-812725645) to fix it.
