### ISSUE TITLE
Install error: archive extraction failed

### ISSUE THREAD

**Issue by rmeno12** [pop-os/pop#1780]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https:/support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**
Whenever I try to install Pop OS, it always fails when trying to extract `/cdrom/casper_pop-os_21.04_amd64_nvidia_debug_14/filesystem.squashfs`. As you can see I'm using the NVIDIA ISO. I've tried multiple times and it always seems to fail with around 34% on the progress bar.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**
I have verified the SHA256 and used three separate USB drives, all of which have the same issue. I have even tried using a separate computer to flash the USB drives. All the USBs were flashed using Balena Etcher.
I am trying to install Pop OS over my previous Ubuntu 20.04 installation, so I used the advanced drive configuration option and manually selected my existing EFI, root, and home partitions.

**Comment by rmeno12** [comment]
[installer.log](https://github.com/pop-os/pop/files/6765159/installer.log)
This is the log from the installer.

**Comment by rmeno12** [comment]
I am also having the same error when trying to install the 20.04 LTS version.

**Comment by leviport** [comment]
This sounds like the bug that was fixed by https://github.com/pop-os/upgrade/pull/182. We are still working on releasing isos with that fix, but for now, try booting the iso with ethernet disconnected.

This issue should not be present in 20.04.

**Comment by leviport** [comment]
If booting without ethernet works, please close as a duplicate of https://github.com/pop-os/beta/issues/153

**Comment by rmeno12** [comment]
I did encounter that bug as well, and booting without ethernet fixed that. However, this is a separate issue and is not resolved by disconnecting ethernet.

**Comment by reginbald** [comment]
What's the status of the ISO release that has the fix?

**Comment by leviport** [comment]
@reginbald the fix for https://github.com/pop-os/beta/issues/153? They have been out for a while now. Version number 6 contains the fix.

**Comment by philburr** [comment]
I hit this issue while installing pop-os_21.10_amd64_nvidia_5.iso.  I was installing over Ubuntu 21.10 without reformatting my partition (I wanted to keep my home folder).  After I got the error and looked at the log, I sha256sum'd the filesystem.squashfs.  I then mounted the iso via loopback on another machine and sha256sum'd the filesystem.squashfs in it.  And I got identical results.  So it wasn't a hardware problem.  Since the log had the unsquashfs command, I did the same to see if I could replicate the error.  And I was.  It was failing to overwrite something in /etc (I don't recall now what).  I realized that the problem was caused by me not reformatting.  So instead I nuked everything in my partition *except* the home folder and redid the install and it worked flawlessly.  Also if you go down this route of not reformatting, also remove the `.config` folder in your home directory for the desktop to work.

**Comment by jwhite2a** [comment]
I ran into the same issue trying to reinstall pop-os_22.04_amd64_nvidia_7.iso from a USB. I was trying to overwrite an existing Pop OS 22.04 installation.

When I selected the option to format the ext4 parition in the Pop OS installation screen, the installation proceeded successfully. This seems to agree with @philburr comments.

**Comment by sammypanda** [comment]
> @sammypanda I haven't seen any reports of this in recent years. It's usually an indication that the ISO was not burned correctly.

Here's 2 posts involving it (2 months ago):
- https://www.reddit.com/r/pop_os/comments/1hetpgv/popos_2204_lts_cant_install/
- https://www.reddit.com/r/pop_os/comments/1gzhstv/installation_error/

Surely something would sound off about trying Pop multiple times with Balena/Rufus and then doing Manjaro once and it working (ISO from the Pop website). That would be a major coincidence. If this isn't a concern, then that's just that.

**Comment by sammypanda** [comment]
@mmstick why would an issue like this show up in a seemingly controlled environment like that? I'm not super convinced it's about the integrity of the ISO; thorough testing *of* the ISO's i'd think is only more of a testament to it being caused by something else.

**Comment by mmstick** [comment]
The moment you download the ISO and flash it onto a USB drive, you're no longer in a controlled environment. Unless you have on our Pop USB drives imaged with Popsicle.

**Comment by MrMustardTBC** [comment]
I ran into this issue today. sha256 verified on the download and the copy I loaded with ventoy. Persists over multiple reboots and attempts.
