### ISSUE TITLE
Wifi Adapter Not Found

### ISSUE THREAD

**Issue by KookiKodes** [pop-os/pop#1866]
```bash
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

This is not an issue with any application or software/package. I've essentially been trying to get the wifi to work on my device and anything I have tried has not had any success whatsoever. I have done my research on the device and confirmed that it works with the kernel within the current version of Pop!_OS (5.11.0-7620-generic). The device I am using, confirmed by running `lspci -nnn`, is "[28:00.0 Network controller [0280]: Intel Corporation Wi-Fi 6 AX200 [8086:2723] (rev 1a)](https://linux-hardware.org/index.php?id=pci:8086-2723-8086-0080)". Now one thing I noticed after running `sudo dmesg | grep iwlwifi` is the following error/notice:
```bash
[   28.861436] iwlwifi 0000:28:00.0: enabling device (0000 -> 0002)
[   28.866886] iwlwifi 0000:28:00.0: api flags index 2 larger than supported by driver
[   28.866894] iwlwifi 0000:28:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 89.3.35.22
[   28.867114] iwlwifi 0000:28:00.0: loaded firmware version 59.601f3a66.0 cc-a0-59.ucode op_mode iwlmvm
[   28.942277] iwlwifi 0000:28:00.0: Detected Intel(R) Wi-Fi 6 AX200 160MHz, REV=0x340
```
It states that the "api flags index 2 larger than supported by driver", which is a little curious to me, but I can't really find much on this issue through a google search. So the device is detected and the bluetooth portion of the device works perfectly, but for some reason the NetworkManager does not pick up the wireless adapter. The motherboard is a [MSI X570 GAMING PRO CARBON AC NON-SLI.](https://www.msi.com/Motherboard/MPG-X570-GAMING-PRO-CARBON-WIFI/Specification). At this point, I'm not too sure what I can do and any assistance with this would be very much appreciated. Thank you ahead of time :) ! I am open to try anything :)

**Comment by ids1024** [comment]
Hm, an AX200 card shouldn't really have any issues. What's the output of `rfkill`? Does `ip link` show the device?

**Comment by KookiKodes** [comment]
Right?!?! Thank you for looking into this for me :) !

Output of rfkill:
```bash
kookikodes@pop-os:~$ rfkill

ID TYPE      DEVICE      SOFT      HARD
 0 bluetooth hci0   unblocked unblocked
 1 wlan      phy1   unblocked unblocked
```

Output of 'ip link':

```bash
kookikodes@pop-os:~$ ip link

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: wlxa09f10bf5546: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether a0:9f:10:bf:55:46 brd ff:ff:ff:ff:ff:ff
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN mode DEFAULT group default qlen 100
    link/none 

```
So, #2 that's listed there is my external wifi adapter I am using to access wifi on the device. I think tun0 (#3) is apart of that device as well. Before I was tethering my mobile device's internet and the output would usually only return `lo` and `eth0`.  Again, thank you for taking interest in this issue.

**Comment by ids1024** [comment]
Hm, nothing obviously useful there.

For `sudo dmesg | grep iwlwifi` (on the current testing build of 21.10) I have:

```
[   15.507334] iwlwifi 0000:00:14.3: api flags index 2 larger than supported by driver
[   15.507348] iwlwifi 0000:00:14.3: TLV_FW_FSEQ_VERSION: FSEQ Version: 89.3.35.37
[   15.507579] iwlwifi 0000:00:14.3: loaded firmware version 63.c04f3485.0 QuZ-a0-hr-b0-63.ucode op_mode iwlmvm
[   15.612685] iwlwifi 0000:00:14.3: Detected Intel(R) Wi-Fi 6 AX201 160MHz, REV=0x354
[   15.798861] iwlwifi 0000:00:14.3: base HW address: 40:ec:99:0d:d0:6d
[   15.813893] iwlwifi 0000:00:14.3 wlp0s20f3: renamed from wlan0
```

The same `api flags index 2 larger than supported by driver`, so that's probably not the problem. And when it's working correctly dmesg should have other lines with the device name (something starting with `wl`), at least when it actually connects to a network.

**Comment by KookiKodes** [comment]
This is the entire message I get from dmesg, the rest is really long, so bare with me xD. This is everything I get from running `sudo dmesg | grep iwlwifi`.

Yeah, it doesn't get those 2 extra lines, with base HW address. I wouldn't begin to know how to resolve this xD.

```bash
kookikodes@pop-os:~$ sudo dmesg | grep iwlwifi
[   22.444229] iwlwifi 0000:28:00.0: enabling device (0000 -> 0002)
[   22.452407] iwlwifi 0000:28:00.0: api flags index 2 larger than supported by driver
[   22.452416] iwlwifi 0000:28:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 89.3.35.22
[   22.452589] iwlwifi 0000:28:00.0: loaded firmware version 59.601f3a66.0 cc-a0-59.ucode op_mode iwlmvm
[   22.564159] iwlwifi 0000:28:00.0: Detected Intel(R) Wi-Fi 6 AX200 160MHz, REV=0x340
[   30.093261] Modules linked in: cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore efi_pstore k10temp mac_hid sch_fq_codel msr parport_pc ppdev lp drm
[   43.699864] Modules linked in: rfcomm nf_tables nfnetlink cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore efi_pstore k10temp mac_hid sch_fq_codel msr
[16519.144305] Modules linked in: snd_seq_dummy hid_logitech_hidpp uhid rfcomm nf_tables nfnetlink cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore
[41738.558790] Modules linked in: snd_seq_dummy hid_logitech_hidpp uhid rfcomm nf_tables nfnetlink cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore
[76905.802175] Modules linked in: snd_seq_dummy hid_logitech_hidpp uhid rfcomm nf_tables nfnetlink cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore
[79420.454932] Modules linked in: snd_seq_dummy hid_logitech_hidpp uhid rfcomm nf_tables nfnetlink cmac algif_hash algif_skcipher af_alg bnep nvidia_uvm(POE) binfmt_misc nvidia_drm(POE) nvidia_modeset(POE) snd_hda_codec_realtek snd_hda_codec_generic ledtrig_audio snd_hda_codec_hdmi snd_hda_intel snd_intel_dspcfg soundwire_intel soundwire_generic_allocation soundwire_cadence intel_rapl_msr intel_rapl_common nvidia(POE) snd_hda_codec iwlmvm snd_hda_core soundwire_bus snd_soc_core mac80211 uvcvideo snd_usb_audio snd_compress btusb videobuf2_vmalloc ac97_bus snd_usbmidi_lib drm_kms_helper btrtl snd_pcm_dmaengine videobuf2_memops snd_hwdep btbcm videobuf2_v4l2 edac_mce_amd wl(POE) btintel nls_iso8859_1 libarc4 videobuf2_common cec 88x2bu(OE) snd_pcm videodev snd_seq_midi iwlwifi input_leds snd_seq_midi_event bluetooth ccp rc_core snd_rawmidi ecdh_generic kvm snd_seq joydev snd_seq_device snd_timer fb_sys_fops mc ecc snd syscopyarea sysfillrect wmi_bmof cfg80211 rapl sysimgblt soundcore
```

**Comment by ids1024** [comment]
Yeah, I'm not sure why it would neither work nor have an error.

It looks like `Modules linked in` should follow some error and precede a call trace. That suggests some issue, but isn't necessarily related to wifi since it's just listing every loaded module.

**Comment by KookiKodes** [comment]
That's what I'm thinking, in other linux based operating systems, I believe it would return an error code of -101. But I still couldn't find much on it in that regards. Could it be a driver issue/firmware issue, because the versions of firmware and hardware are not exactly the same? If so, I wonder if I should just try working with Intel?

**Comment by ids1024** [comment]
I might see if it's the same with other distros (just testing networking in the live USB system should be sufficient). If it were an issue I could reproduce, that's probably what I'd do; see if the latest Ubuntu and Fedora have the same issue, in which case there's probably nothing for Pop!_OS specifically to do about it (nor an issue with the system's specific configuration).

In which case, and given it works on Windows, I guess it would be a `linux` or `linux-firmware` issue.

**Comment by KookiKodes** [comment]
Alrighty, I'll see how it responds to other linux distros. If it is a linux or linux-firmware issue, where would I post this issue so it could potentially get fixed in the future?

**Comment by ids1024** [comment]
I guess just https://bugzilla.kernel.org/. Though I'm still not sure exactly what about the system would lead to the issue since the AX200 itself is probably fairly common and well tested now.

**Comment by KookiKodes** [comment]
Well this is bizarre, I had a power outage that shutdown my pc and now all of the sudden the wifi is working without the usb adapter xD.
