### ISSUE TITLE
System freezes when opening Application Launcher

### ISSUE THREAD

**Issue by duck-dev** [pop-os/pop#2110]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Application Launcher/Library

**Issue/Bug Description:**

I just updated from Pop! OS 21.04 to 21.10. The update seemed to be successful. After the reboot, I had to re-enable the Dash-To-Panel plugin again, so I can get my customized taskbar back, which seemed to disappear after the update (which shouldn't be the case in my opinion, unless there is a specific reason to it).
After I've done that, I tried to open the Application Launcher/Library, which caused the entire system to freeze. I could only move my mouse, otherwise nothing worked, no keyboard shortcuts, nothing. I tried to reboot and do the same thing again - same issue. Nothing responds.

**Steps to reproduce (if you know):**

- Upgrade to 21.10
- Try to open Application Launcher from the taskbar after the reboot

**Expected behavior:**

The system should obviously not freeze if I want to use the Application Launcher. :)

**Other Notes:**

I'm really sorry if I opened this issue in the wrong repository. I'm not sure where such a report would fit the best. 
From all the "freeze reports" all over the internet and Pop! OS repositories, they all seemed to happen randomly at some time. In my case however, it happens with no other applications running, almost the entire memory is available and in a specific situation (when trying to open the Application Launcher), not "randomly" as other people often describe.

This only happened after the 21.10 update and I didn't touch the hardware before/in-between. That's why I highly doubt it's specifically a hardware issue, that's triggered by the attempt to open the Application Launcher (through the taskbar).

**System Specifications:**
CPU: Intel® Core™ i7-3770 CPU @ 3.40GHz × 8 
RAM: 15.6 GB (16 GB, 4 x 4 GB RAM)
GPU: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB]
HDD: Works fine, 2 TB
SSD: Works fine, 2 x 128 GB

**Comment by 13r0ck** [comment]
> I had to re-enable the Dash-To-Panel plugin again, so I can get my customized taskbar back, which seemed to disappear after the update (which shouldn't be the case in my opinion, unless there is a specific reason to it

After upgrades, extensions are removed, that behavior is intended by GNOME.

**Comment by 13r0ck** [comment]
This may have been fixed. Run `sudo apt update && sudo apt upgrade -y && reboot`, after the reboot does that fix the issue?

If not:
How are the accessing the application library?
What is the output of `apt policy gnome-shell-extension-cosmic-workspaces`?
If you press (Alt + F2) and type `r` then press enter `enter` does the issue go away?

If (Alt + F2) fixes the issue, can you please paste the output of `journalctl -b 0 | grep gnome-shell` here?

**Comment by duck-dev** [comment]
Hello @13r0ck , thank you very much for reaching out to me.

- Running `sudo apt update && sudo apt upgrade -y && reboot` doesn't fix the issue.
- I'm not quite sure about your question, but I just want to access it with the symbol in the taskbar (see image below, the middle one):
![grafik](https://user-images.githubusercontent.com/61479436/151195018-43d672f4-8693-4d59-b745-0a6db890af96.png)
- The output of `apt policy gnome-shell-extension-cosmic-workspaces` is:
```
gnome-shell-extension-cosmic-workspaces:
  Installiert:           0.1.0~1642187850~21.10~09d34c6
  Installationskandidat: 0.1.0~1642187850~21.10~09d34c6
  Versionstabelle:
 *** 0.1.0~1642187850~21.10~09d34c6 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```
- Pressing ALT + F2, typing `r` and pressing `Enter` doesn't fix the issue either.

It still crashes.
