### ISSUE TITLE
Keyboard lag and missing key presses

### ISSUE THREAD

**Issue by SpeckledPingu** [pop-os/pop#2247]
**Distribution**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

Laptop type: Galago

**Issue/Bug Description:**
On rebooting today, my laptop's keyboard's behavior has significant lag and will miss keystrokes. For example, if typing asdf, it might only return sdf. It will also only allow 3-5 characters to be typed before another lagging period happens. Sometimes (not always) it requires multiple presses of the key. It's behavior is not the same as sticky keys or slow keys and I have confirmed that these accessibility options are off.

This is not the case for a Bluetooth keyboard which operates just fine.

Furthermore, since the reboot, it does look like gnome tweaks has had certain issues too. In the power/wifi/settings dropdown on the menu top bar, there are no longer options for GPU settings or power settings or displays the battery percentage. On top of this, Gnome Tweaks does not show any effect on this drop down after toggling the options. This is true even after reinstalling tweaks.

This has happened once before, and it was fixed by a full re-install so it does not appear to be a physical keyboard issue. But an OS refresh (just performed too), did not have any impact on this behavior.

**Comment by leviport** [comment]
Which generation is your Galago? (ex. galp3, galp4, ...)

**Comment by leviport** [comment]
I'm unable to replicate keyboard lag or missed characters on our lab unit, so I don't think this is a widespread problem. I recommend opening a support ticket so our support team can help you investigate the issue.

Another good debugging step would be to see if the same thing happens when booting into the recovery partition. If it does not, then that might point to something misconfigured within your installed OS.

**Comment by alex-o-a** [comment]
I had a similar issue after installing a new instance - Turns out it was just the typing assist messing with it. Settings > Accessibility >> Typing > typing assist.

**Comment by emansom** [comment]
> **Same here, fixed the problem.** I've never touched this setting. Has enabled instead of disabled become the default for this setting?

However, the keyboard experience suffers greatly with typing assist off.

When overall system utilization is low, the problem doesn't appear. I suspect some part of GNOME and/or an extension is allocating memory or doing CPU intensive things on the critical input handling path.

**Comment by maxnewbould** [comment]
This also started around the same time as first reported

![image](https://user-images.githubusercontent.com/100380/228852475-567b6283-bc5f-4c53-9c9f-089f4bd991a5.png)

**Comment by ClaireDMT** [comment]
Thanks @maxnewbould , for me it was a month ago. I will install another distro to be sure it's POP OS and not something else.
I tried to verify what keys were logged/detected with screenkey and it shows some doubled or non-detected key press. 
I use an external keyboard now. So I am thinking about changing OS as I bought my PC not a year ago and with no OS, so that's a bit of a waste/shame

**Comment by markagonzales** [comment]
I also have a galp5 and have recently started experiencing the same issue where not all key presses are registering. This started in the last 2 weeks or so. The big difference in usage is I've decided to run the machine as a server and have it pulled in and on all the time.

The missing key presses is very much noticeable when booting the laptop and entering my user password to decrypt the drive.

**Comment by ClaireDMT** [comment]
Update on that. After some updates it was gone for 3 months. And it's back since last month. Definitively not hardware...

**Comment by borjaevo** [comment]
Same problem here, very frustrating. Main keyboard on laptop works ok, but external USB keyboard is repeating or laging keys. Changing USB port improves a little bit for some time. Typing assist is disabled.

**Comment by scsumpter** [comment]
> same problem here with keys `asdjkl`, randomly not working. I rebooted, and I got the problem on recovery mode too.

Same problem. Especially the 'A' key. Switching to a new field to type in, often misses first keypress, sometimes a missed keypress will register later and show up in the middle of a word.

![image](https://github.com/pop-os/pop/assets/137903823/a28894a2-fa2f-42b8-a119-6a5cd7bc9cf9)

**Comment by ibndias** [comment]
my case was it is laggy on sublime, visual code, and chrome.

But very responsive on terminal, i also tried to turn on screenkey, key press was indeed detected.

But some apps does not detect it.

**Comment by eureka-cpu** [comment]
I've had this problem with all of my keyboards on pop for a while now, only on my nvidia laptop. I recently updated my drivers and it's so much worse now 😂 Here's my info if it helps.

```
OS: Pop!_OS jammy 22.04 x86_64
Kernel: Linux 6.9.3-76060903-generic
DE: GNOME 42.9
WM: Mutter (X11)
CPU: 12th Gen Intel(R) Core(TM) i7-12800H (20) @ 4.80 GHz
GPU 1: NVIDIA Geforce RTX 3070 Ti Laptop GPU
GPU 2: Intel Iris Xe Graphics @ 1.40 GHz [Integrated]
```

**Comment by ibndias** [comment]
> my case was it is laggy on sublime, visual code, and chrome.
> 
> But very responsive on terminal, i also tried to turn on screenkey, key press was indeed detected.
> 
> But some apps does not detect it.

Okay, it is solved now. The problem was: _I accidentally turned on "Screen Reader" somehow_. I have never used my speaker nor my headphone so I did not know that the whole time it reads everything in my screen and that why it hangs when I open megabytes of text data.

So after clicking the "gear icon" in the top right panel, and turn off "Screen Reader", the problem was gone.

**Comment by boundless-forest** [comment]
I encountered the same issue while using Pop!_OS 22.04 and searched extensively for a solution. Eventually, I discovered that it might be a problem with the default input method, ibus. Switching to Fcitx5 resolved the issue. This may be helpful to others who are facing the same problem.

**Comment by lorenzokraft** [comment]
This is 2025! Nothing here works for me, this issue still exists on PopOs, I dual boot windows on the same PC & my External and Internal keyboards work well on the other side(Windows) but when switching back to PopOs, Keyboard lag and missing key presses occur (For example when I type 'Root' simultaneously, only one 'o' makes it to the screen)
