### ISSUE TITLE
Install PopOS Freezes on 22.04

### ISSUE THREAD

**Issue by KennyDevT** [pop-os/pop#2429]
**Distribution (run cat /etc/os-release)**:
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 

**Issue/Bug Description:**
When I click select on the popOs installer it Freezes and this is on the language select I got it to work once but it just froze again when I was at choosing the type of installation 

**Steps to reproduce (if you know):**
Flash POPOS Intel amd on to 64 gb flash drive using balena

**Expected behavior**
Install without Freezes

**Comment by mmstick** [comment]
It freezes for the duration that it's scanning disks on the system for installations.

**Comment by KennyDevT** [comment]
Even on the language select?

**Comment by mmstick** [comment]
That is the precise moment that it does a scan.

**Comment by KennyDevT** [comment]
Ok so how come it Freezes when you select the type of installation

**Comment by Seibz** [comment]
What hardware are you experiencing this on?

**Comment by KennyDevT** [comment]
Hp stream 2018 with Intel celeron n4000 ,  intel hd graphics 600 and 4gb ram

**Comment by armincxh** [comment]
I'm having the same problem

**Comment by Seibz** [comment]
As that hardware is a bit limited by the RAM and possibly the processor, are you able to install a lightweight distro such as Xubuntu 22.04? Pop!_OS may be a bit heavy for that hardware. Have you also tried a different USB drive?

**Comment by aindriu80** [comment]
I'm having the same problem, Pop OS 22.04 won't install on my desktop, I have got Manjaro and Ubuntu to work but not Pop OS 22.04, 21.10 or 21.04.  I'm running a Ryzen 3600, Radeon 6600, 512GB Samsung 970 M.2 drive, 32GB of 3200mhz RAM on a B550 Aorus V2 Pro, I do have 1 other SSD and 3 mechanical disks in my computer.

The installer stops when selecting a language.  I think it does this because it is reading all my drives, I have unplugged all my USB connections and removed all drives except the m.2 but it still doesn't do the installation.  It might be because it is a dual boot with Windows 11.

**Comment by Seibz** [comment]
For those in this issue running the old HP Steam hardware from 2018 with 4gb of RAM, I would recommend you install a different distro. For the Ryzen 3600 user, what brand of RAM do you have in that machine?

**Comment by aindriu80** [comment]
I finally got Pop!_OS installed on my desktop - the solution was to disconnect all my SATA connections to my motherboard,  also plug out all USB connections except for keyboard and mouse.  It seems as though POP starts scanning all drives and ports and becomes unresponsive in the process - I've tried other distros in the meantime and they also suffer from this, it seems as though the installer they are all using is highly suspect.  One other thing you can try is disconnect the Internet, make the installation the simplest for the installer.

**Comment by KennyDevT** [comment]
issue was fixed by pop os it seems

**Comment by Eris7090** [comment]
> 

definitely not, I just downloaded an image today and it's still freezing

**Comment by bslaterdk** [comment]
I have the exact same issue, it simply freezes when selecting the install language.
Other distro's I tried worked without any issues.
And I just downloaded the latest ISO (nvidia version)

**Comment by leo1mml** [comment]
I can also confirm this is happening using the nvidia install. Should this be reopened?

**Comment by tofazzz** [comment]
I tried today as well and can confirm same issue with PopOS 22.04

**Comment by LexouDuck** [comment]
Please reopen this issue. Things are still freezing (LiveUSB with pop-os 22.04 LTS), and there is no feedback to the user (like a loading bar) to indicate that a long and costly operation is taking place (in this case, checking which disk partitions exists).

This is very poor user experience design - similar to the pop-shop, which hangs crashes every other minute.

**Comment by tannercrook** [comment]
I am also experiencing this issue.
Dual Boot. Nvidia.

I have tried unplugging drives without success. I would agree that it would go a long way to have a "Please wait while we scan your drives." type of message. I left it for a day and it never finished.

**Comment by stegaBOB** [comment]
@KennyDevT I am getting this issue as well. At the same time. Dual boot RTX 3080 and 5900x. Freezes during the language install.

**Comment by Double0Beagle** [comment]
Hello
Same issue by my side. I've a RTX 3080Ti, Ryzen 5600 32Gb ram 3600Mhzn Nvidia ISO. It freezes at multiple step, sometimes on language selection, sometimes when I click on "Advanced" (when asking for a full install or a advanced one), and sometimes when GParted is open ...

**Comment by doxxedd** [comment]
Mine doesn't freeze but after selecting keyboard layout, it kicks me out of the installer and shows a gnome login screen (kinda like it logged out). Now it wants a username? But it's a live usb...

**Comment by NemyV** [comment]
Clean installed PopOS on SSD 2 days ago. I experienced freezes during installation as well but on community pages they said its normal. Random freezes just keep happening during workflow no matter what i do. I also experience lose of focus when i try to type something inside shop search box and other. Sometimes freeze is temporary but mostly it forces a restart...

**Comment by KennyDevT** [comment]
Apparently people still have this issue

**Comment by leo1mml** [comment]
I don't know if it's something local to my machine, but this problem has happened with me on every linux install. After I added the `pci=nomsi` to the grub parameters before the install it was gone.

**Comment by tannercrook** [comment]
As a follow-up to experiencing the freeze immediately after selecting the keyboard/language. I used a different flash drive, a different brand of flash drive to be specific and everything worked perfect and was instant. The one failing was a SanDisk. Formatted the very same as the one that worked.

**Comment by Auxority** [comment]
This bug also occurs on Ubuntu, seems to be an issue with Ubuntu 22.04.

**Comment by bp0** [comment]
I had this issue in a laptop with two drives. One had a windows 10 install on it and the other was to have Pop OS. The situation was that Windows had not shut down but only hibernated, and the kernel was refusing to mount it for the scanner because of that state. Disabling the windows drive temporarily let the installer work without any problem.

**Comment by KennyDevT** [comment]
Sorry miss clicked

**Comment by ThiagoMowszet** [comment]
I found this video: https://www.youtube.com/watch?v=kBMRw7j4tlg
In the comments says if we are using popOS, we need to run this command: 
**_sudo kernelstub -o "pcie_aspm=off"_**
Hope this helps someone!

**Comment by eladio77** [comment]
Hi .. i had the same problem. I Open a top console and see a process consuming resourses. The process name is 'ntfsresizing ' i end the process and the install process continuid. I was able to install the system .

I think is a problem when You hace Windows partitions in your pc

**Comment by lucyamonster** [comment]
Hi i have had these freezes in the language selection menu. Normaly they woud hapen all trough out the process, but now im just getting spikes on the cpuloadgraffs but none of the processes running report more then zero percent of cpu usage.

Specs:
Intel® Core™ i7-8550U CPU @ 1.80GHz × 8
NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile]

**Comment by Paranoia8972** [comment]
The thing that worked for me was upgrading everything. So just open the terminal and run `sudo apt update && sudo apr upgrade -y`. This should fix the problem.

**Comment by KitsuneAlex** [comment]
Experiencing this on a Lenovo IdeaPad 110-15ISK 80UD with an Intel i5 6200U, 12GB of RAM and a 120GB SSD.
The device is plugged in to the wall and ethernet with internet access.
Downloaded the latest Intel ISO today and booted off a decently fast USB3 thumbdrive.
Sadly, none of the aforementioned workarounds do it for me as of right now. I will update this comment if i find anything.

**Comment by KitsuneAlex** [comment]
> As a follow-up to experiencing the freeze immediately after selecting the keyboard/language. I used a different flash drive, a different brand of flash drive to be specific and everything worked perfect and was instant. The one failing was a SanDisk. Formatted the very same as the one that worked.

That is really odd, mine is a SanDisk too.. but i already swapped it for another one once and the result was the same :/

**Comment by KitsuneAlex** [comment]
> Experiencing this on a Lenovo IdeaPad 110-15ISK 80UD with an Intel i5 6200U, 12GB of RAM and a 120GB SSD. The device is plugged in to the wall and ethernet with internet access. Downloaded the latest Intel ISO today and booted off a decently fast USB3 thumbdrive. Sadly, none of the aforementioned workarounds do it for me as of right now. I will update this comment if i find anything.

For me it turned out to be a dead-ish SSD. I swapped it out for a new(er) one and everything worked fine. So in most cases it seems to be either the installation medium or one of the permanently installed drives.

**Comment by AndrewScudder** [comment]
Attempting to install pop, when get booted into the usb, the Installer launcher is crashing on the selection  of the country.

I have tried multi usb sticks with and Ventoy and etcher.

**Comment by sayandipdutta** [comment]
Why does it not say that it is scanning a disk? That would save countless collective hours from being wasted.

**Comment by Solidesphere** [comment]
Still crashing

**Comment by EF-Code** [comment]
I first installed on a blank SSD and it wasn't crashing but installing on the same SSD with an NTFS partition causes it to freeze/crash. Killing ntfsresize fixes it (sudo kill ntfsresize), you might need to do it a couple of times i.e when it freezes.
