### ISSUE TITLE
Broken language pack dependencies?

### ISSUE THREAD

**Issue by matrix8967** [pop-os/pop#2553]
**Distribution (run `cat /etc/os-release`):**
 
 `Pop!_OS 22.04 LTS`
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
language-pack-gnome-en:
  Installed: 1:22.04+20220415
  Candidate: 1:22.04+20220721
  Version table:
     1:22.04+20220721 500 (phased 20%)
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/main i386 Packages
 *** 1:22.04+20220415 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

I'm having the same issue with the following packages as well:

```
language-pack-ar
language-pack-de
language-pack-fr-base
language-pack-gnome-ar-base
language-pack-gnome-en
language-pack-gnome-es
language-pack-gnome-ja-base
language-pack-gnome-pt
language-pack-gnome-zh-hans
language-pack-ja
language-pack-pt-base
language-pack-ru-base
language-pack-zh-hans
```

**Issue/Bug Description:**

Packages are being held back. The usual `apt` trickery (autoclean, dist-upgrade, --fix-missing) aren't working. I saw a post with a similar issue on reddit so I figured it might be an upstream repo issue.

**Steps to reproduce (if you know):**

`sudo apt update && sudo apt upgrade -y`

**Expected behavior:**

Successful package upgrade.

**Other Notes:**

When I tried to manually install *ALL* the packages (and their dependencies) manually - I get the following output:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 language-pack-ar : Depends: language-pack-ar-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-de : Depends: language-pack-de-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-fr-base : Depends: language-pack-fr (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
                         Conflicts: language-pack-fr (< 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-gnome-ar-base : Depends: language-pack-gnome-ar (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
                               Conflicts: language-pack-gnome-ar (< 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-gnome-en : Depends: language-pack-gnome-en-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-gnome-es : Depends: language-pack-gnome-es-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-gnome-ja-base : Depends: language-pack-gnome-ja (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
                               Conflicts: language-pack-gnome-ja (< 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-gnome-pt : Depends: language-pack-gnome-pt-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-ja : Depends: language-pack-ja-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-pt-base : Depends: language-pack-pt (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
                         Conflicts: language-pack-pt (< 1:22.04+20220721) but 1:22.04+20220415 is to be installed
 language-pack-zh-hans : Depends: language-pack-zh-hans-base (>= 1:22.04+20220721) but 1:22.04+20220415 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mmstick** [comment]
Ubuntu is doing phased updates. Notice the `(Phased 20%)` messaging. You're not allowed to install it until it's your turn in the queue.

**Comment by jacobgkau** [comment]
Should be fixed by https://github.com/pop-os/default-settings/pull/152 once that's released.

**Comment by pbui** [comment]
Hmm... even after https://github.com/pop-os/default-settings/pull/152, I am still getting phased updates showing up.  After doing a `sudo apt update` today, I get the following:

```
$ sudo apt update
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Hit:2 http://apt.pop-os.org/release jammy InRelease
Hit:3 http://apt.pop-os.org/ubuntu jammy InRelease
Hit:4 http://apt.pop-os.org/ubuntu jammy-security InRelease
Hit:5 http://apt.pop-os.org/ubuntu jammy-updates InRelease
Hit:6 http://apt.pop-os.org/ubuntu jammy-backports InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
19 packages can be upgraded. Run 'apt list --upgradable' to see them.

$ sudo apt list --upgradable
Listing... Done
libegl-mesa0/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libegl-mesa0/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
libegl1-mesa-dev/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libegl1-mesa/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libgbm1/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libgbm1/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
libgl1-mesa-dri/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libgl1-mesa-dri/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
libgl1-mesa-glx/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libglapi-mesa/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libglapi-mesa/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
libglx-mesa0/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
libglx-mesa0/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
libxatracker2/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
mesa-va-drivers/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
mesa-va-drivers/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]
mesa-vdpau-drivers/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
mesa-vulkan-drivers/jammy-updates 22.0.5-0ubuntu0.1 amd64 [upgradable from: 22.0.1-1ubuntu2.1]
mesa-vulkan-drivers/jammy-updates 22.0.5-0ubuntu0.1 i386 [upgradable from: 22.0.1-1ubuntu2.1]

$ sudo apt policy libegl-mesa0
libegl-mesa0:
  Installed: 22.0.1-1ubuntu2.1
  Candidate: 22.0.5-0ubuntu0.1
  Version table:
     22.0.5-0ubuntu0.1 500 (phased 20%)
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
 *** 22.0.1-1ubuntu2.1 100
        100 /var/lib/dpkg/status
     22.0.1-1ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        
$  cat /etc/apt/apt.conf.d/76pop-default-settings 
APT::Get::Never-Include-Phased-Updates "true";
```

If I switch the configuration to `APT::Get::Always-Include-Phased-Updates "true";`, then that appears to work and allows me to get all the phased updates.
