### ISSUE TITLE
PC Freezes After Suspend

### ISSUE THREAD

**Issue by lucashtc** [pop-os/pop#2605]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
Kernel=5.19.0-76051900-generic
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Whenever I suspend my desktop and wake it back up, it becomes unresponsive. I always have to press the off button to turn off and on again my way out.

**Steps to reproduce (if you know):**
Suspend the machine and resume use after pressing the power button

**Expected behavior:**

**Other Notes:**

**Comment by skythomp16** [comment]
This is also happening for me.  I noticed that the nvidia-suspend services are not running and when enabling them with systemctl, they end up dead shortly after.  I think this has something to do with the nvidia cards.  Do you have a NVIDIA card in your machine?

**Comment by lucashtc** [comment]
I don't have an NVIDIA blueprint.
I think I'll also disable suspension until they find a solution to this problem.

**Comment by leviport** [comment]
Can you describe your hardware?

**Comment by skythomp16** [comment]
My hardware- 
CPU: Ryzen 5800X
GPU: RTX 3070 TI
RAM: 128GB 3200mhz ddr4
MOBO: ASUS Prime B450M
SSD:  Samsung 980 PRO 2TB boot drive

**Comment by lucashtc** [comment]
CPU: Intel i5-8250U (8) @ 3.400GHz
GPU: Intel UHD Graphics 620
Memory: 5975MiB / 7806MiB
Latitude 5490

**Comment by ProjectInitiative** [comment]
related: #2616  #2608 #2605
possibly related: #2607 #2598

**Comment by ZorkotLinda** [comment]
Check #2607

**Comment by leviport** [comment]
@ZorkotLinda that was already linked in the comment above yours. Thank you for helping to link potentially related issues together, but please be careful not to spam them.

**Comment by skythomp16** [comment]
I switched out my 3070TI to an old RX 580 I had laying around and now suspend works just fine. FYI for me it was nvidia drivers.

**Comment by lucashtc** [comment]
I have fixed it. I basically disabled POP!_os powermanagement and let Linux do it itself.

Go into extensions and disable System76 Power extension

1. systemctl stop system76-power
2. systemctl disable system76-power
3. Reboot

Since the last updates, the problem seems to have gotten worse.

**Comment by javadevmtl** [comment]
Same here.

**Comment by mabhijithn** [comment]
> I have fixed it. I basically disabled POP!_os powermanagement and let Linux do it itself.
> 
> Go into extensions and disable System76 Power extension
> 
>     1. systemctl stop system76-power
> 
>     2. systemctl disable system76-power
> 
>     3. Reboot
> 
> 
> Since the last updates, the problem seems to have gotten worse.

Unfortunately, this solution has not solved it for me. When I suspend my PC, the PC goes to suspend for a second then freezes. No signal to the monitor, cannot wake it up. I have to power off my desktop PSU and power it back on to get it back online! That is just painful!
My OS details:
```NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```


My hardware configuration:
CPU: AMD Ryzen 5 5600
GPU: Nvidia GTX 1050Ti
Motherboard: Aorus B550M
RAM: 16GB 3200MHz

**Comment by lucashtc** [comment]
This problem is very painful.
to get rid of this problem, I ended up testing a new distro (Fedora 37)

**Comment by jamesvrt** [comment]
What do you think of Fedora 37 on an NVIDIA laptop so far?

**Comment by blackbicbiro** [comment]
I am in the same boat with an XPS15, Crashes after ever standby. will try disabling system76 power

**Comment by preslavrachev** [comment]
> I have fixed it. I basically disabled POP!_os powermanagement and let Linux do it itself.
> 
> Go into extensions and disable System76 Power extension
> 
>     1. systemctl stop system76-power
> 
>     2. systemctl disable system76-power
> 
>     3. Reboot
> 
> 
> Since the last updates, the problem seems to have gotten worse.

I've recently experienced the same problem, and this solution seems to have fixed it. My hardware is a bit unusual (MacBook Pro 2015), so I thought it's probably hardware-specific, but I couldn't recall this happening with every previous version.

As others have reported, disabling `system76-power` leads to a pretty significant batter drop while the laptop is suspended. In my case, we are talking about 15-20% battery per night. My battery is brand new - it got replaced about a week ago, so I doubt that it is related to that - most likely services keep running in the background even during suspension.

Please, update this thread, if `system76-power` gets fixed in a new update. I'd be happy to enable it again.

**Comment by rschlack** [comment]
I'm seeing this happen on mine after reinstalling POP on an HP Dev One.   It's all AMD so nothing to do with Nvidia.

**Comment by JHrenyk** [comment]
I'm having the same issue. I have it narrowed down to having my Nvidia GPU enabled in BIOS and suspending on battery power. If i suspend while I am plugged in I can wake up no problem.  If i suspend on battery I am forced to hard restart it by holding the off button.

**Comment by rschlack** [comment]
I solved this by downgrading the kernel to 5.x from 6.x.   I have tried a few distros and this happens to me in every distro with the 6.x kernel.

**Comment by ppriyankuu** [comment]
so that means no fixed solution has been found till now. btw I am facing the same issue.

**Comment by kevinforrestconnors** [comment]
I fixed this by disabling suspend.

**Comment by riziry** [comment]
have you guys tried to use sleep or hibernate? i think there something wrong in system76 power management suspend, basically sleep will consume more power than suspend, and hibernate not consume power at all but saving everything in disk rather than ram

**Comment by raytsou** [comment]
Hi, I am also experiencing this issue on a fresh install of Pop and would like to document for help debugging.

To reiterate, the issue is that after I `systemctl suspend`, I am stuck in a blank, black screen on wakeup that I cannot interact with. `ctrl` + `alt` + `F3` does not work and unplugging/repluggging the monitor also has no effect.

My system is:
- OS: Pop!_OS 22.04 LTS x86_64
- Kernel: 6.9.3-76060903-generic
- DE: GNOME 42.9
- Motherboard: X570 Phantom Gaming-ITX/TB3
- CPU: AMD Ryzen 7 5700X3D
- GPU: NVIDIA GeForce GTX 1080 Ti
- Memory: 64225MiB
- Nvidia Driver Version: 560.35.03

Here's how I fixed it:
1. I found [this](https://www.reddit.com/r/pop_os/comments/1f73ozv/comment/lqbux5e/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) reddit comment suggesting running:
```
sudo systemctl disable nvidia-hibernate

sudo mkdir -p /var/run/nvidia-sleep
sudo chown nvidia-persistenced:nvidia-persistenced /var/run/nvidia-sleep
```
2. I did that, after which I tried to test via `systemctl suspend`. I still had a black screen on wakeup. So I rebooted.
3. Next I tried what was described in [this comment](https://askubuntu.com/a/1409631) linked from the reddit comment. This involves:
i. Running:
```
sudo systemctl disable nvidia-suspend
sudo systemctl disable nvidia-resume
sudo systemctl disable nvidia-hibernate
```
ii. Changing `/usr/bin/nvidia-sleep.sh` to
```
#!/bin/bash
exit 0
```
4. Then I tried `systemctl suspend` and was able to wake up successfully.

I'm not actually sure if (3) fixed it or if (1) followed by a reboot fixed it, so detailing both.

**Comment by pipegalera** [comment]
I had the same issue with a dedicated nvidia gpu and X11. The following worked for me.

I created a configuration file that set kernel module parameters for the NVIDIA driver:

```
sudo nano /etc/modprobe.d/nvidia-power-management.conf
```

I wrote in it the following to preserve the video memory allocations when suspending/resuming the system and prevent graphics memory issues after system sleep:

```
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp
```

After rebooting no more black screens

**Comment by mtolmacs** [comment]
I can confirm that @pipegalera's solution worked perfectly for PopOS 24.04 too (with the COSMIC Alpha 4 version). This is a laptop (XMG NEO) with discrete RTX 3070 P + external monitor on HDMI.

**Comment by pupuklangka** [comment]
@pipegalera solution work for me, I am using hardware : 

> 00:00.0 Host bridge: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers (rev 0d)
> 00:01.0 PCI bridge: Intel Corporation 6th-10th Gen Core Processor PCIe Controller (x16) (rev 0d)
> 00:12.0 Signal processing controller: Intel Corporation Cannon Lake PCH Thermal Controller (rev 10)
> 00:14.0 USB controller: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller (rev 10)
> 00:14.2 RAM memory: Intel Corporation Cannon Lake PCH Shared SRAM (rev 10)
> 00:16.0 Communication controller: Intel Corporation Cannon Lake PCH HECI Controller (rev 10)
> 00:17.0 SATA controller: Intel Corporation Cannon Lake PCH SATA AHCI Controller (rev 10)
> 00:1c.0 PCI bridge: Intel Corporation Cannon Lake PCH PCI Express Root Port #8 (rev f0)
> 00:1f.0 ISA bridge: Intel Corporation H310 Chipset LPC/eSPI Controller (rev 10)
> 00:1f.3 Audio device: Intel Corporation Cannon Lake PCH cAVS (rev 10)
> 00:1f.4 SMBus: Intel Corporation Cannon Lake PCH SMBus Controller (rev 10)
> 00:1f.5 Serial bus controller: Intel Corporation Cannon Lake PCH SPI Controller (rev 10)
> **01:00.0 VGA compatible controller: NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] (rev a1)**
> **01:00.1 Audio device: NVIDIA Corporation GP107GL High Definition Audio Controller (rev a1)**
> 02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet Controller (rev 15)

**Comment by sloik-production** [comment]
I'm not sure, but can be this relative to the issue?
https://github.com/rpmfusion/xorg-x11-drv-nvidia/blob/master/disable_freeze_user_session.conf

**Comment by hogmat** [comment]
Had this issue. [This](https://github.com/pop-os/pop/issues/2605#issuecomment-2526281526) solution by @pipegalera fixed it.

```
NAME="Pop!_OS"
VERSION="24.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 24.04 LTS"
VERSION_ID="24.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=noble
UBUNTU_CODENAME=noble
LOGO=distributor-logo-pop-os
```

Some hardware info:
```
H/W path           Device           Class          Description
==============================================================
                                    system         ASUS TUF Gaming F17 FX707ZV4_FX707ZV4
/0                                  bus            FX707ZV4
/0/0                                memory         64KiB BIOS
/0/3b                               memory         32GiB System Memory
/0/3b/0                             memory         16GiB SODIMM DDR4 Synchronous 3200 MHz (0.3 ns)
/0/3b/1                             memory         16GiB SODIMM DDR4 Synchronous 3200 MHz (0.3 ns)
/0/48                               memory         288KiB L1 cache
/0/49                               memory         192KiB L1 cache
/0/4a                               memory         7680KiB L2 cache
/0/4b                               memory         24MiB L3 cache
/0/4c                               memory         256KiB L1 cache
/0/4d                               memory         512KiB L1 cache
/0/4e                               memory         4MiB L2 cache
/0/4f                               memory         24MiB L3 cache
/0/50                               processor      12th Gen Intel(R) Core(TM) i7-12700H
/0/100                              bridge         12th Gen Core Processor Host Bridge/DRAM Registers
/0/100/1                            bridge         12th Gen Core Processor PCI Express x16 Controller #1
/0/100/1/0         /dev/fb0         display        AD107M [GeForce RTX 4060 Max-Q / Mobile]
/0/100/1/0.1       card0            multimedia     NVIDIA Corporation
/0/100/1/0.1/0     input26          input          HDA NVidia HDMI/DP,pcm=3
/0/100/1/0.1/1     input27          input          HDA NVidia HDMI/DP,pcm=7
/0/100/1/0.1/2     input28          input          HDA NVidia HDMI/DP,pcm=8
/0/100/1/0.1/3     input29          input          HDA NVidia HDMI/DP,pcm=9
/0/100/2                            display        Alder Lake-P GT2 [Iris Xe Graphics]
```

I also have an external monitor connected with an USB dock. This has caused me pain with most distros. :-)

**Comment by Doct0rLekter** [comment]
> I had the same issue with a dedicated nvidia gpu and X11. The following worked for me.
> 
> I created a configuration file that set kernel module parameters for the NVIDIA driver:
> 
> ```
> sudo nano /etc/modprobe.d/nvidia-power-management.conf
> ```
> 
> I wrote in it the following to preserve the video memory allocations when suspending/resuming the system and prevent graphics memory issues after system sleep:
> 
> ```
> options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp
> ```
> 
> After rebooting no more black screens

This also occurs with an AMD Graphics card, any idea of similar fixes?
