### ISSUE TITLE
systemd-journald freezes the computer and uses most of the CPU

### ISSUE THREAD

**Issue by jlangson** [pop-os/pop#2849]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 22.04 LTS
 
**Related Application and/or Package Version (run `apt policy systemd):**
Installed: 249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb
  Candidate: 249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb
  Version table:
     249.11-0ubuntu3.7 500
        500 http://apt.pop-os.org/ubuntu jammy-security/main amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
 *** 249.11-0ubuntu3.6pop0~1674074077~22.04~d0333cb 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     249.11-0ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

**Issue/Bug Description:**
Sometimes the computer will freeze and the GUI will become unresponsive. When I switch to a terminal (ctrl alt f3), `top` shows the cpu is being hogged by `systemd-journald`. When I kill systemd-journald, it restarts. When I renice systemd-journald, it makes no difference in cpu consumption.

**Steps to reproduce (if you know):**
Leave computer on until systemd-journald runs.

**Expected behavior:**
systemd-journald runs and the GUI does not freeze. if I kill it, it does not restart.

**Other Notes:**

**journalctl**

> Mar 28 18:14:00 pop-os systemd-journald[595]: Suppressed 2255 messages from session-2.scope
> Mar 28 18:15:39 pop-os systemd-journald[595]: Suppressed 19832 messages from session-2.scope
> Mar 28 18:16:28 pop-os systemd-journald[595]: Suppressed 6060 messages from session-2.scope
> Mar 28 18:17:01 pop-os CRON[86010]: pam_unix(cron:session): session opened for user root(uid=0) by (uid=0)
> Mar 28 18:17:01 pop-os CRON[86011]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
> Mar 28 18:17:01 pop-os CRON[86010]: pam_unix(cron:session): session closed for user root
> Mar 28 18:17:17 pop-os systemd-journald[595]: Suppressed 6003 messages from session-2.scope
> Mar 28 18:18:07 pop-os systemd-journald[595]: Suppressed 8457 messages from session-2.scope
> Mar 28 18:18:56 pop-os systemd-journald[595]: Suppressed 22669 messages from session-2.scope
> Mar 28 18:19:46 pop-os systemd-journald[595]: Suppressed 5685 messages from session-2.scope
> Mar 28 18:20:35 pop-os systemd-journald[595]: Suppressed 5520 messages from session-2.scope
> Mar 28 18:21:24 pop-os systemd-journald[595]: Suppressed 18379 messages from session-2.scope
> Mar 28 18:22:14 pop-os systemd-journald[595]: Suppressed 12855 messages from session-2.scope
> Mar 28 18:22:57 pop-os systemd[1]: Starting Ubuntu Advantage Timer for running repeated jobs...
> Mar 28 18:22:57 pop-os systemd[1]: ua-timer.service: Deactivated successfully.
> Mar 28 18:22:57 pop-os systemd[1]: Finished Ubuntu Advantage Timer for running repeated jobs.
> Mar 28 18:23:03 pop-os systemd-journald[595]: Suppressed 5730 messages from session-2.scope
> Mar 28 18:23:52 pop-os systemd-journald[595]: Suppressed 6339 messages from session-2.scope
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "640x480"x0.0   31.50  640 656 720 840  480 481 484 500 -hsync -vsync (37.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "640x480"x0.0   31.50  640 664 704 832  480 489 492 520 -hsync -vsync (37.9 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "640x480"x0.0   30.24  640 704 768 864  480 483 486 525 -hsync -vsync (35.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "720x400"x0.0   28.32  720 738 846 900  400 412 414 449 -hsync +vsync (31.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1280x1024"x0.0  135.00  1280 1296 1440 1688  1024 1025 1028 1066 +hsync +vsync (80.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1024x768"x0.0   78.75  1024 1040 1136 1312  768 769 772 800 +hsync +vsync (60.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1024x768"x0.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "800x600"x0.0   49.50  800 816 896 1056  600 601 604 625 +hsync +vsync (46.9 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080"x120.0  368.76  1920 2072 2288 2656  1080 1081 1084 1157 -hsync +vsync (138.8 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1440x900"x0.0  182.75  1440 1488 1520 1600  900 903 909 953 +hsync -vsync (114.2 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1024x768"x0.0  115.50  1024 1072 1104 1184  768 771 775 813 +hsync -vsync (97.6 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "800x600"x0.0   73.25  800 848 880 960  600 603 607 636 +hsync -vsync (76.3 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "640x480"x120.0   52.41  640 680 744 848  480 481 484 515 -hsync +vsync (61.8 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1280x1024"x0.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1440x900"x0.0   88.75  1440 1488 1520 1600  900 903 909 926 +hsync -vsync (55.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): EDID vendor "PHL", prod id 49348
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Using hsync ranges from config file
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Using vrefresh ranges from config file
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Printing DDC gathered Modelines:
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync (67.5 kHz eP)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "720x480"x0.0   27.00  720 736 798 858  480 489 495 525 -hsync -vsync (31.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1280x720"x0.0   74.25  1280 1390 1430 1650  720 725 730 750 +hsync +vsync (45.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "640x480"x0.0   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080"x0.0   74.25  1920 2558 2602 2750  1080 1084 1089 1125 +hsync +vsync (27.0 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080"x0.0  148.50  1920 2448 2492 2640  1080 1084 1089 1125 +hsync +vsync (56.2 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1280x720"x0.0   74.25  1280 1720 1760 1980  720 725 730 750 +hsync +vsync (37.5 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "720x576"x0.0   27.00  720 732 796 864  576 581 586 625 -hsync -vsync (31.2 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080i"x0.0   74.25  1920 2008 2052 2200  1080 1084 1094 1125 interlace +hsync +vsync (33.8 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1920x1080i"x0.0   74.25  1920 2448 2492 2640  1080 1084 1094 1125 interlace +hsync +vsync (28.1 kHz e)
> Mar 28 18:23:56 pop-os /usr/libexec/gdm-x-session[2936]: (II) AMDGPU(0): Modeline "1440x480i"x0.0   27.00  1440 1478 1602 1716  480 488 494 525 interlace -hsync -vsync (15.7 kHz e)

**hardware**

Graphics card - product: Navi 14 [Radeon RX 5500/5500M / Pro 5500M]
CPU - AMD Ryzen 5 5600G with Radeon Graphics

**Comment by leviport** [comment]
We just released a systemd update today, version `249.11-0ubuntu3.7pop1~1680050939~22.04~c5d2663`. Perhaps that will behave better?

**Comment by HintringerFabian** [comment]
I have a similar problem with Kernel 6.2.6-76060206-generic and 6.2.6-76060200

The system gets stuck after some time. First time it happened was 11.04.2023. 
The screen just gets stuck and i cannot do anything, but restart the laptop.

At the moment i cannot confirm it happens because of systemd-journald, but i will if it freezes the next time. It also happened today after i updated my system.

![image](https://user-images.githubusercontent.com/79401071/231975168-04d09e96-90c7-4a29-939d-0239ffeda25e.png)


**System Information**
**Laptop**: Asus Tuf Gaming A17
**OS Version**: Pop!_OS 22.04 LTS
**Kernel Version**: 6.2.6-76060206-generic
**uname -a**: Linux pop-os 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux
**CPU**: Ryzen 7 4800H
**GPU**: GTX 1660 TI Mobile
**RAM**: 16GB  
**Drive**: NVME SSD 
![image](https://user-images.githubusercontent.com/79401071/231972113-094cacfb-da72-45e7-b867-0680f449edd7.png)

Log output will be added as soon as it happens again.

**Comment by HintringerFabian** [comment]
These are my logs right before the crash

```
Apr 15 11:31:43 pop-os kernel: [  200.172188] general protection fault, probably for non-canonical address 0x176d178860869208: 0000 [#1] PREEMPT SMP NOPTI
Apr 15 11:31:43 pop-os kernel: [  200.172203] CPU: 14 PID: 8288 Comm: Action Updater  Tainted: G        W  OE      6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4
Apr 15 11:31:43 pop-os kernel: [  200.172208] Hardware name: ASUSTeK COMPUTER INC. ASUS TUF Gaming A17 FA706IU_FA706IU/FA706IU, BIOS FA706IU.316 03/12/2021
Apr 15 11:31:43 pop-os kernel: [  200.172212] RIP: 0010:__kmem_cache_alloc_node+0x1e1/0x340
Apr 15 11:31:43 pop-os kernel: [  200.172224] Code: 20 5b 41 5c 41 5d 41 5e 41 5f 5d 31 d2 89 d1 89 d6 89 d7 41 89 d0 41 89 d1 e9 eb d4 c9 00 41 8b 44 24 28 4d 8b 04 24 48 01 f8 <48> 8b 18 48 89 c1 49 33 9c 24 b8 00 00 00 48 89 f8 48 0f c9 48 31
Apr 15 11:31:43 pop-os kernel: [  200.172228] RSP: 0018:ffffbd5312317e50 EFLAGS: 00010202
Apr 15 11:31:43 pop-os kernel: [  200.172233] RAX: 176d178860869208 RBX: 0000000000000dc0 RCX: 00000000000000b0
Apr 15 11:31:43 pop-os kernel: [  200.172237] RDX: 0000000006d3800e RSI: 0000000000000dc0 RDI: 176d1788608691a8
Apr 15 11:31:43 pop-os kernel: [  200.172239] RBP: ffffbd5312317e98 R08: 0000000000036100 R09: 0000000000000000
Apr 15 11:31:43 pop-os kernel: [  200.172243] R10: 0000000000000000 R11: 0000000000000000 R12: ffffa03cc0042800
Apr 15 11:31:43 pop-os kernel: [  200.172245] R13: 0000000000000dc0 R14: 00000000ffffffff R15: 00000000000000b0
Apr 15 11:31:43 pop-os kernel: [  200.172248] FS:  00007fc0966ff640(0000) GS:ffffa03fdf980000(0000) knlGS:0000000000000000
Apr 15 11:31:43 pop-os kernel: [  200.172251] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Apr 15 11:31:43 pop-os kernel: [  200.172254] CR2: 00007fc0e40c8ec8 CR3: 0000000260b0e000 CR4: 0000000000350ee0
Apr 15 11:31:43 pop-os kernel: [  200.172257] Call Trace:
Apr 15 11:31:43 pop-os kernel: [  200.172260]  <TASK>
Apr 15 11:31:43 pop-os kernel: [  200.172262]  ? do_epoll_create+0x68/0x1b0
Apr 15 11:31:43 pop-os kernel: [  200.172269]  kmalloc_trace+0x2a/0xb0
Apr 15 11:31:43 pop-os kernel: [  200.172275]  do_epoll_create+0x68/0x1b0
Apr 15 11:31:43 pop-os kernel: [  200.172278]  __x64_sys_epoll_create1+0x11/0x20
Apr 15 11:31:43 pop-os kernel: [  200.172282]  do_syscall_64+0x5b/0x90
Apr 15 11:31:43 pop-os kernel: [  200.172288]  ? syscall_exit_to_user_mode+0x29/0x50
Apr 15 11:31:43 pop-os kernel: [  200.172292]  ? do_syscall_64+0x67/0x90
Apr 15 11:31:43 pop-os kernel: [  200.172295]  entry_SYSCALL_64_after_hwframe+0x72/0xdc
Apr 15 11:31:43 pop-os kernel: [  200.172302] RIP: 0033:0Apr 15 11:32:12 pop-os kernel: [    0.000000] Linux version 6.2.6-76060206-generic (jenkins@warp.pop-os.org) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A

**Comment by HintringerFabian** [comment]
Actually my problem was resolved, when refreshing the OS

**Comment by jlangson** [comment]
> We just released a systemd update today, version `249.11-0ubuntu3.7pop1~1680050939~22.04~c5d2663`. Perhaps that will behave better?

It worked fine for about a month, but today the problem came back. @leviport 

Also, how can I kill systemd-journald so it doesn't restart?

**Comment by jeff-j-chen** [comment]
Can confirm same issue, it's been happening to me for years; it will occur occasionally after I press the super key to get Workspaces and I am simply forced to restart. I thought it was to do with extensions (Just Perfection, Dash to Dock for Cosmic) and disabling those helped with frequency, but the issue still persists.

**Comment by ev-agelos** [comment]
> Can confirm same issue, it's been happening to me for years; it will occur occasionally after I press the super key to get Workspaces and I am simply forced to restart. I thought it was to do with extensions (Just Perfection, Dash to Dock for Cosmic) and disabling those helped with frequency, but the issue still persists.

Same here but instead of restarting i open a new tty (ctrl+alt+f3) and kill the gnome-shell. Killing the journal even with -9 does nothing. Then go back to desktop tty (ctrl+alt+f2, might be f1 for others) and in a couple of seconds like 1-2 gnome-shell restarts by itself.
