### ISSUE TITLE
Nvdia 580 driver causes black second monitor on 22.04 and Wayland

### ISSUE THREAD

**Issue by arzilloa** [pop-os/pop#3610]
OS: Pop_OS 22.04 
Kernel: 6.16.3-76061603-generic
Driver: nvidia-driver-580-open 580.82.09-1pop1~1759280886~22.04~48c237e
Display protocol: Wayland
GPU:  RTX-4060

After the last system update that upgraded to nvidia-580-open driver package, I am no longer able to use my second monitor, which was working fine with nvidia-570 drivers. The second monitor shows only a black screen with a visible mouse cursor.

Key details:
- Issue occurs specifically with nvidia-580-open package
- Both monitors worked perfectly with nvidia-570 
- Primary monitor functions normally
- Second monitor is detected, but displays only black screen + cursor
- Attempted full driver uninstall/reinstall with no success

Questions:
-Why was nvidia-570 removed from repos and replaced with a transitional package pointing to nvidia-580?

**Comment by MaFra001** [comment]
I can confirm this to be the case on my hybrid laptop (RTX3060 + AMD Radeon integrated graphics). And since there's no way to go back to nvidia-driver-570, I/m stuck with one screen (laptop screen, which uses built-in AMD GPU).

The above-mentioned behavior is only for Wayland session, X11 works correctly but it's not usable for me due to having a mix of 4k and 1920p displays.

**Comment by infalmo** [comment]
I'm unable to install the update altogether - nvidia-driver-580 depends on nvidia-driver-580-open which isn't configured yet or the likes. Any way to patch fix this quickly?

**Comment by MaFra001** [comment]
> I'm unable to install the update altogether - nvidia-driver-580 depends on nvidia-driver-580-open which isn't configured yet or the likes. Any way to patch fix this quickly?

This a different issue altogether. You have closed Nvidia drivers installed while trying to install open ones (or vice-versa). This might be an issue with updated drivers but it's not the issue we reported here - please open the separate ticket to not pollute this one.

**Comment by grubasek3D** [comment]
OS: Pop!_OS 24.04 LTS
Kernel: 6.16.3-76061603-generic
Driver: nvidia-driver-580-open 580.82.09-1pop1175928088622.04~48c237e
Display protocol: Wayland
GPU: NVIDIA Corporation TU104GLM [Quadro RTX 4000 Mobile / Max-Q] (rev a1) / Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)

I have similar issues with external displays. And it was present also with the 570 drivers.

So I am connected through Thunderbolt (3 in my Thinkpad P1 laptop and g4 hp dock). I am experimenting now with different `system76-power graphics` as the hybrid is not working especially well for my case.

Do you have any hints on that?

I'll refer to the first comment:
Key details:

* Issue occur with nvidia-580-open package and nvidia-570
* Primary monitor functions normally
* Second monitor is detected, but displays only black screen and monitor goes sleep (no cursor or whatever)
* Attempted full driver uninstall/reinstall with no success
* If only one (of two) external monitors is on (with internal and other external off) the switch off and on appears randomly

**Comment by awee85** [comment]
@arzilloa  I had similar problems with 580 branch can you checkin dmesg and / or journalctl if you have same error messages?  -> flip event timeout

https://github.com/pop-os/nvidia-graphics-drivers/issues/250

**Comment by lattarov** [comment]
I have the exact same issue here, with  575.64.05, 580.82.07 or 580.82.09 versions of the drivers, but up to the 570 versions everything worked flawlessly. 

OS: Pop!_OS 22.04 LTS x86_64 
Host: Victus by HP Laptop 16-d0xxx 
Kernel: 6.16.3-76061603-generic 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
Wayland session
HDMI connection to the second monitor
**NVIDIA driver: 580.82.09** 

Edit: I can get the mouse to go and be displayed in the second monitor, but nothing else is rendered there: 

![Image](https://github.com/user-attachments/assets/025c8b7c-eef4-4a26-8233-d00672d1d9f8)

And the snipping tool can get images from the second monitor: 

<img width="1653" height="534" alt="Image" src="https://github.com/user-attachments/assets/e331d96b-e460-4a9f-9e2a-f3578284eeb0" />

**Comment by awisse** [comment]
Other issue with the new Nvidia driver: Suspend doesn't work anymore on the System76 Gazelle 17 with Pop!_OS 22.04 LTS. The following log messages repeat in /var/log/syslog:

```
Oct  9 10:35:50 pop-os kernel: [ 4017.647130] NVRM: GPU 0000:01:00.0: PreserveVideoMemoryAllocations module parameter is set. System Power Management attempted without driver procfs suspend interface. Please refer to the 'Configuring Power Management Support' section in the driver README.
Oct  9 10:35:50 pop-os kernel: [ 4017.647144] nvidia 0000:01:00.0: PM: pci_pm_suspend(): nv_pmops_suspend [nvidia] returns -5
Oct  9 10:35:50 pop-os kernel: [ 4017.647953] nvidia 0000:01:00.0: PM: dpm_run_callback(): pci_pm_suspend returns -5
Oct  9 10:35:50 pop-os kernel: [ 4017.647964] nvidia 0000:01:00.0: PM: failed to suspend async: error -5
Oct  9 10:35:50 pop-os kernel: [ 4017.680592] PM: Some devices failed to suspend, or early wake event detected
```

**Comment by awee85** [comment]
> Oct  9 10:35:50 pop-os kernel: [ 4017.647130] NVRM: GPU 0000:01:00.0: PreserveVideoMemoryAllocations module parameter is set. System Power Management attempted without driver procfs suspend interface. Please refer to the 'Configuring Power Management Support' section in the driver README.

that is a easy fix.. enabling PreserveVideoMemoryAllocations without proper suspend support in your case. just enable:  nvidia-suspend.service, nvidia-hibernate.service, and nvidia-resume.service

**Comment by awisse** [comment]
> that is a easy fix.. enabling PreserveVideoMemoryAllocations without proper suspend support in your case. just enable: nvidia-suspend.service, nvidia-hibernate.service, and nvidia-resume.service

Turns out these three services are already enabled. Just got a step from System76 customer support that fixed it for me: Disable `PreserveVideoMemoryAllocations`:

`echo 'options nvidia NVreg_PreserveVideoMemoryAllocations=0' | sudo tee /etc/modprobe.d/nvidia-power.conf`

**Comment by MaFra001** [comment]
So today, I got the new update for nvidia drivers but the situation remains the same - still black screen on second monitor , with only the cursor being shown.

**Comment by infalmo** [comment]
Turned off RAM/CPU overclocking and my issues were solved.

**Comment by MaFra001** [comment]
I don't have any overclocking turned on. The issue with black screen and only a mouse cursor visible is still present after the latest update from System76. No change. 
If nothing changes in a couple of days, I might be forced to switch to another distro, unfortunately. X11 is not usable for me since I have mixed-DPI screens and X11 is locking my laptop from time to time. And this makes me sad since Pop OS! has been stable and fast so far on this machine.

**Comment by amit177** [comment]
Deleting the system76 package and installing the driver from NVIDIA's website was the workaround for me (until this is fixed in pop)

**Comment by awee85** [comment]
> Deleting the system76 package and installing the driver from NVIDIA's website was the workaround for me (until this is fixed in pop)

Yes indeed what I did. I installed the Nvidia-Driver from XanMod and Suspend/Resume is now working. I did not close my issue because the fix is not in pop os made :) 

I think they need at least version 580.95.05 thats the one which is playing nice on my pop os 24.04

fyi:

```
nvidia-smi
Sat Oct 11 17:43:25 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Quadro T2000                   Off |   00000000:01:00.0  On |                  N/A |
| N/A   51C    P8              3W /   35W |     115MiB /   4096MiB |      9%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2359      G   cosmic-comp                               3MiB |
+-----------------------------------------------------------------------------------------+
anton@P1GEN2TUX /etc/apt/preferences.d>
```

**Comment by awee85** [comment]
I'm curious to see how long this will last. I've never had good experiences with external repositories, especially when it comes to large, system-relevant packages like graphics card drivers. I then gave the xanmod repo such a high priority that you can clearly see it here in the policy output: xanmod with 1000, ahead of the pop os sources for their nvidia driver version with 1001. I'm curious to see how long you can run something like this before the system crashes because of something or takes ages to repair, but I have a backup and can simply roll back when pop os has a better driver available.



```
anton@P1GEN2TUX ~> apt-cache policy nvidia-driver-580-open
nvidia-driver-580-open:
  Installiert:           580.95.05-0xanmod1
  Installationskandidat: 580.82.09-1pop1~1759962949~24.04~eb2851e
  Versionstabelle:
 *** 580.95.05-0xanmod1 1000
       1000 http://deb.xanmod.org noble/non-free amd64 Packages
        100 /var/lib/dpkg/status
     580.82.09-1pop1~1759962949~24.04~eb2851e 1001
       1001 http://apt.pop-os.org/release noble/main amd64 Packages
anton@P1GEN2TUX ~>
```

**Comment by MaFra001** [comment]
I didn't want to install nvidia's own drivers (out of pop os' repo) since it's always a gamble if it will go alright and then it's a pain to remove them properly. In the end I decided to do an upgrade to Pop OS 24.04 beta, which, curiously, has the same kernel and nvidia drivers version but works flawlessly since Saturday. Let's see if it continues like that. 
I can say that I'm impressed with speed and overall look and feel, compared to 22.04 but it's too early to comment on stability.

**Comment by avislash** [comment]
I get the same behavior with the 580 drivers

OS: PoP 22.04
Kernel: 6.12.10-76061203-generic
Chip: RTX 4050

**Comment by m0thgurl** [comment]
also getting the same issue with 580 specifically, didnt try the workarounds since id prefer an official fix, but the current drivers im using with the latest Pop!_OS build works just fine

OS: Pop!_OS 22.04
Kernel: 6.16.3-76061603-generic
GPU: RTX 5060 Ti

**Comment by csaba-valentin** [comment]
I also have the same issue with 580. The 575 driver worked fine with external monitor with HDMI-> HDMI and with type-c -> HDMI.

OS: Pop!_OS 22.04 LTS
Kernel: 6.16.3-76061603-generic #202508231538~1758561135~22.04~171c8de
GPU: NVIDIA GeForce RTX 5070 Ti Laptop
