### ISSUE TITLE
When waking from sleep, the keyboard repeat rate seems to reset back to the default

### ISSUE THREAD

**Issue by nerdo** [pop-os/pop#598]
**Distribution (run `cat /etc/os-release`):**
``` 
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I have customized my keyboard repeat rate and delay under Settings->Universal Access->Typing->Repeat Keys.

When I close the lid on my laptop and put it to sleep, then wake it up again, the keyboard settings seem to reset.

**Steps to reproduce (if you know):**
1. Customize keyboard repeat rate and delay under Settings->Universal Access->Typing->Repeat Keys.
2. Put computer in sleep/suspend mode.
3. Wake computer.
4. Attempt to type and observe whether or not it has kept the customized settings.

**Expected behavior:**
I expect it to keep the customized settings.

**Other Notes:**
My workaround for now is to go back into Settings->Universal Access->Typing->Repeat Keys and toggle it off and back on.

**Comment by goodmami** [comment]
Is there any update or upstream bug for this? I'm running 20.04 and I'm still affected by this bug. Every time I wake from suspend or attach a keyboard to my laptop (both bluetooth and USB) it resets the repeat rate to some unbearably slow default.

To clarify, the steps to reproduce do not need a suspend/resume cycle; all I need to do is turn off my bluetooth keyboard (or unplug a USB one) then reattach.

**Comment by jacobgkau** [comment]
> edit: after commenting I came across this: https://gitlab.gnome.org/GNOME/mutter/-/issues/1466. Maybe a fix is on the way?

Yes, this sounds like the same issue as https://github.com/pop-os/gnome-control-center/issues/120 / https://github.com/pop-os/pop/issues/1301 and it should be fixed when that Mutter fix makes its way into stable packages.

**Comment by johnnymatthews** [comment]
Sorry for digging up an old (ancient) issue, but I'm still experiencing this problem in 22.04. What steps can I take to debug further?

**Comment by kodmanyagha** [comment]
That god damn bug still exist and this is so annoying me.
