### ISSUE TITLE
Dummy/bogus entry "(null) Developers" in Pop!_Shop's Updates after a clean 20.04 install

### ISSUE THREAD

**Issue by dcominottim** [pop-os/pop#946]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-shop:
  Installed: 3.1.1pop0~1588203946~20.04~f106def
  Candidate: 3.1.1pop0~1588203946~20.04~f106def
  Version table:
 *** 3.1.1pop0~1588203946~20.04~f106def 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

There appears a dummy or bogus entry with title "(null) Developers" in the Installed section.

**Steps to reproduce (if you know):**

Clean install 20.04, update everything through cli or Pop!_Shop, then restart and open Pop!_Shop and the Installed tab.

**Expected behavior:**

Entry ""(null) Developers" shouldn't exist or should have a clear title and description.

**Other Notes:**

**Comment by leviport** [comment]
Thanks for the report. This was being tracked here: https://github.com/pop-os/beta/issues/108 

It was fixed, so you should see the null driver go away after installing updates and rebooting.

**Comment by dcominottim** [comment]
Thanks for the reply, but it doesn't fix it. I've updated everything once again this morning, rebooted multiple times, and it's still there.

**Comment by bizsimon** [comment]
I too still have this issue and have updated everything
